### ISSUE TITLE
Maven 3-jdk-8 image not found in the registry.

### ISSUE THREAD

**Issue by brunoliveira8** [carlossg/docker-maven#100]
When I run

`docker pull maven:3-jdk-8`

I receive the following output:
```
3-jdk-8: Pulling from library/maven
no matching manifest for unknown in the manifest list entries
```

It stopped to work today maybe after the update.

![image](https://user-images.githubusercontent.com/4175481/50899961-eaef5b80-1413-11e9-9491-08944694a038.png)

I tested `maven:3-jdk-10` and `maven:3` and it's working.

**Comment by carlossg** [comment]
It failed the first time I tried but works now

**Comment by brunoliveira8** [comment]
I confirm it's back. I was trying periodically for about 1 hour.

Thanks @carlossg.
