### ISSUE TITLE
Update jdk8 images to >= 8u191

### ISSUE THREAD

**Issue by idkw** [carlossg/docker-maven#102]
Hi,

Some maven images for jdk-8 (especially 3.6.0-jdk-8) are still using Java 8u181, whereas the latest version is 8u202.

All versions using java < 8u191 are broken relative to this issue : https://github.com/carlossg/docker-maven/issues/90

Can you update them all at least to 8u191, if not 8u202 ?

Thank you

**Comment by carlossg** [comment]
there's no `openjdk:8-jdk` with those versions yet, see https://github.com/docker-library/openjdk/issues/272
