### ISSUE TITLE
Is there an image for maven version 3.0.5 ?

### ISSUE THREAD

**Issue by NikhilNanjappa** [carlossg/docker-maven#103]
My project needs exactly maven version `3.0.5`.

Hence, in my `Dockerfile`, I am trying to use the official maven image from dockerhub (https://hub.docker.com/_/maven) but I couldn’t find the `3.0.5` version image. So, my question is - Is there any image for maven version `3.0.5` that I can use in my `Dockerfile` ?

If not, could someone please provide me an alternative ?

**Comment by carlossg** [comment]
there is not, you have to build it yourself
