### ISSUE TITLE
arm64 build failing

### ISSUE THREAD

**Issue by vielmetti** [carlossg/docker-maven#106]
see https://doi-janky.infosiftr.net/job/multiarch/job/arm64v8/job/maven/110/ 

the salient error message is

```
command: docker push "arm64v8/maven:3.6.0-jdk-7-alpine"
received unexpected HTTP status: 500 Internal Server Error
```

@tianon I wonder if this is a real failure, or if something was flaky!

**Comment by tianon** [comment]
That seems like it's probably something that happened during the time the
Hub was having some issues; I've kicked it again to hopefully get something
moving.

**Comment by vielmetti** [comment]
Looks like the build is green again! Thanks @tianon !
