### ISSUE TITLE
Docker for maven:3.6.1

### ISSUE THREAD

**Issue by bbqrob** [carlossg/docker-maven#107]
Since 4th April there's Maven 3.6.1, please add a docker container for this.

**Comment by mdiskin** [comment]
I'm able to pull this for corretto-11 but not for 8.
`C:\>docker pull maven:3.6-amazoncorretto-11
3.6-amazoncorretto-11: Pulling from library/maven
Digest: sha256:943ab5b4dd8e1b7344b2468a1d6ee810c0b68933af8a76232026a6663cf20c40
Status: Downloaded newer image for maven:3.6-amazoncorretto-11

C:\>docker pull maven:3.6.1-amazoncorretto-11
3.6.1-amazoncorretto-11: Pulling from library/maven
Digest: sha256:943ab5b4dd8e1b7344b2468a1d6ee810c0b68933af8a76232026a6663cf20c40
Status: Image is up to date for maven:3.6.1-amazoncorretto-11

C:\>docker pull maven:3.6-amazoncorretto-8
3.6-amazoncorretto-8: Pulling from library/maven
Digest: sha256:5a68e55ff3a094a8da906da245bf49bc3e639d349b0932436d38ebb3603dcedc
Status: Image is up to date for maven:3.6-amazoncorretto-8

C:\>docker pull maven:3.6.1-amazoncorretto-8
Error response from daemon: manifest for maven:3.6.1-amazoncorretto-8 not found`

**Comment by carlossg** [comment]
see https://github.com/docker-library/official-images/pull/5747

**Comment by carlossg** [comment]
fixed with https://github.com/docker-library/official-images/pull/5774
