### ISSUE TITLE
/root/.m2 should not be a volume

### ISSUE THREAD

**Issue by nvdk** [carlossg/docker-maven#11]
The [Dockerfile documentation](https://docs.docker.com/engine/reference/builder/) specifies that `If any build steps change the data within the volume after it has been declared, those changes will be discarded.`

By declaring `/root/.m2/` as a volume it is no longer possible to extend the maven dockerfile and do `mvn install` during build as all the installed packages will be discarded unless you specify a different local maven repository. 

If you choose to keep the volume declaration for some reason, then at least make it clear in the documentation that a user extending the image should use a different local maven repository.

**Comment by carlossg** [comment]
Generally speaking it should be a volume, out of the union filesystem. If you run it as a volume then doesn't matter what you put in there in the image.
What can be done is a entrypoint script to copy files from another location in the image into the volume on startup the same way it is done in the jenkins image.

I don't recall if there is some other official image requirement to have it a volume in the image or letting people just mount at runtime, maybe @tianon can chime in

**Comment by carlossg** [comment]
Added a script to copy /usr/share/maven/ref/ contents into .m2 dir on startup
The readme explains how to build images with a cached repo

**Comment by nvdk** [comment]
awesome thanks :)

**Comment by tianon** [comment]
Sorry for the late response!  In general, I agree that data bits should be in a volume, although with a "language" / "runtime support" image like this, it might make more sense to add that to the documentation.  It's always a bit of a fine balance given that we can't "undo" a volume. :disappointed:

**Comment by avivian** [comment]
When will the above changes be available in the official images on docker hub?

**Comment by martycurran** [comment]
Hi
I have the dockerfile in same location as pom file building an image when I run the image it gives an error  that there is no pom file in this directory (/). Do I need to put or copy the pom file or Dockerfile to a different directory
