### ISSUE TITLE
jdk-12+ does not contain git

### ISSUE THREAD

**Issue by Stianhn** [carlossg/docker-maven#110]
I've been using 3.6.1-jdk-11 to build my projects and are now upgrading to java 12, but I disocvered that this version does not contain git. Is this removed on purpose or are there an image where both java 12 and git is available?

**Comment by carlossg** [comment]
maybe it was removed from the base image `openjdk:12-jdk`

**Comment by Stianhn** [comment]
Yes, it looks like they changed base os to oraclelinux. Would it be relevant to add a version that includes git since there are several maven plugins that requires git?

**Comment by carlossg** [comment]
Yes, it is oraclelinux https://github.com/docker-library/openjdk/blob/master/12/jdk/oracle/Dockerfile

I'm not sure I would include git as this is the minimal official image, unless there is a number of people voting (:+1) for this issue

**Comment by Stianhn** [comment]
Are there other official images that includes git?

**Comment by stefan-it** [comment]
@Stianhn Currently not. We decided to build our own Maven image based on AdoptOpenJDK, because we cannot live with this Oracle Linux...

**Comment by matthew-formosa-gig** [comment]
We use the maven release plugin as part of our CI/CD process and the plugin uses git commands so an official release with git would surely be ideal :)

**Comment by jglick** [comment]
> We use the maven release plugin as part of our CI/CD process

I am so sorry.

> the plugin uses git commands

Something like the following may be helpful to @matthew-formosa-gig (untested):

```xml
<properties>
  <maven-scm.version>1.11.2</maven-scm.version>
</properties>
<build>
  <plugins>
    <plugin>
      <artifactId>maven-release-plugin</artifactId>
      <configuration>
        <providerImplementations>
          <git>jgit</git>
        </providerImplementations>
      </configuration>
      <dependencies>
        <dependency>
          <groupId>org.apache.maven.scm</groupId>
          <artifactId>maven-scm-provider-jgit</artifactId>
          <version>${maven-scm.version}</version>
        </dependency>
      </dependencies>
    </plugin>
    <plugin>
      <artifactId>maven-scm-plugin</artifactId>
      <version>${maven-scm.version}</version>
      <configuration>
        <providerImplementations>
          <git>jgit</git>
        </providerImplementations>
      </configuration>
      <dependencies>
        <dependency>
          <groupId>org.apache.maven.scm</groupId>
          <artifactId>maven-scm-provider-jgit</artifactId>
          <version>${maven-scm.version}</version>
        </dependency>
      </dependencies>
    </plugin>
  </plugins>
</build>
```

**Comment by matthew-formosa-gig** [comment]
Thanks for the suggestion @jglick but unfortunately, due to certain limitations of the release plugin, we need to run git commands following the `release:prepare` to suit our workflow.

**Comment by jglick** [comment]
:man_shrugging: You can always define a derivative image with any tools you might need to run as subprocesses of `mvn` due to the misconceived design of `maven-release-plugin`. Acc. to [this](https://stackoverflow.com/a/27674776/12916):

```dockerfile
FROM maven:3.6.1-jdk-12
RUN yum install -y http://opensource.wandisco.com/centos/7/git/x86_64/wandisco-git-release-7-2.noarch.rpm && \
    yum install -y git
```

**Comment by carlossg** [comment]
only jdk-8 and jdk-11 have git, every other image doesn't

**Comment by Roberdvs** [comment]
Any chance on getting git on images with JDKs > 11 or do we resort to building custom images?

**Comment by O5ten** [comment]
Building custom images for every company/squad/person is not ideal. 
I think we'd all prefer if it was already present in the image.

**Comment by O5ten** [comment]
We took the decision to put an extended docker image that includes git, scp, openssh and friends and put that internally hosted image registry on a higher priority than docker-hub. Hopefully this will lead to less surprises like this in the future too.

**Comment by kuldeepiitg** [comment]
maven:3.9.0-eclipse-temurin-17-focal worked for me.

I needed Java-17, git and maven
