### ISSUE TITLE
Build settings.xml with env variables to handle proxy

### ISSUE THREAD

**Issue by ebuildy** [carlossg/docker-maven#112]
Running under a proxy, :

```
docker run -ti --rm -e HTTP_PROXY=... -e NO_PROXY=... maven compile test
```

What about generate the settings.xml proxy part from env?

**Comment by ykfq** [comment]
This maybe helpful:
```bash
docker run -ti --rm -e MAVEN_OPTS='-Dhttp.proxyHost=172.31.0.214 -Dhttp.proxyPort=3128 -Dhttps.proxyHost=172.31.0.214 -Dhttps.proxyPort=3128' maven compile test
```

**Comment by ebuildy** [comment]
Yes you are right, I am dreaming of "standard" with Docker images ^^  (by standard I mean it will be a good thing to have the same behavior with gradle / maven etc... images)
