### ISSUE TITLE
Failing to create symbolic link

### ISSUE THREAD

**Issue by ekmaughan** [carlossg/docker-maven#113]
Starting today, I have begun to get an error whenever I try to build the Docker image for this reason:
Step 9/23 : RUN ln -s /etc/java-11-openjdk /usr/lib/jvm/java-11-openjdk-$(dpkg --print-architecture)/conf
 ---> Running in 677d5a65ffe6
ln: failed to create symbolic link '/usr/lib/jvm/java-11-openjdk-amd64/conf': No such file or directory

I'm assuming that this was caused by an update to the openjdk image, but I cannot be sure. Any insight would be much appreciated!

**Comment by carlossg** [comment]
yes, there has been a lot of changes in the openjdk image https://github.com/docker-library/openjdk/pull/322
