### ISSUE TITLE
Volumes not mounted when container is launched from "dockerized" jenkins

### ISSUE THREAD

**Issue by commandantmarcos** [carlossg/docker-maven#12]
Volumes mentionned in my dockerfile are mounted when I launch "docker run -v src:src" (with related VOLUME arguments into my dockerfile) from my host, but not mounted (those from my jenkins workdir of course) when the same command is launched from a dockerized jenkins (I launch my run command using the "add build step" jenkins feature).

I tried to mount my jenkins "$WORKDIR/src" folder with no success so I added my java sources "manually" with ADD. This works fine but as i don't have any mounted volume, I can't bring back my built artifacts (war files) in my jenkins workdir.

I can't send them too to another network shared drive cause ssh not working.

**Comment by commandantmarcos** [comment]
I post one of various Dockerfile config i used.
[Dockerfile.bak.txt](https://github.com/carlossg/docker-maven/files/155427/Dockerfile.bak.txt)

And the working one but with condamned artifacts
[Dockerfile.txt](https://github.com/carlossg/docker-maven/files/155432/Dockerfile.txt)
(And sorry for my english...)

**Comment by carlossg** [comment]
That's not an issue with this image, I think you are trying to run jenkins in a docker container and running this image in the same docker daemon. The volumes are mounted from the host where the daemon runs, not from the container where you are running jenkins
