### ISSUE TITLE
maven-3.6 jdk 12 does not have wget

### ISSUE THREAD

**Issue by bhatnagarm** [carlossg/docker-maven#125]
Maven docker image 3.6.2-jdk-12, 3.6-jdk-12 does not have wget application. All the previous versions of Maven had that.

**Comment by carlossg** [comment]
3.6.1 didn't have it either. You can use `curl`

```
docker run -ti --rm maven:3.6.1-jdk-12 wget
/usr/local/bin/mvn-entrypoint.sh: line 50: exec: wget: not found
```

**Comment by bhatnagarm** [comment]
Thanks for the response. The latest image was working with wget. But I guess curl would work as well.
