### ISSUE TITLE
Switch to Alpine Linux

### ISSUE THREAD

**Issue by rafalwrzeszcz** [carlossg/docker-maven#13]
Are there any plans for introducing Alpine Linux builds? Locally, by just switching from `openjdk-8-jdk` to `openjdk-8-jdk-alpine` (had to add `curl` and `tar` installation) it reduced image size from over 600MB to just 150 MB:

```
$ docker images
REPOSITORY          TAG                    IMAGE ID            CREATED             SIZE
<none>              <none>                 bf36783f4f83        6 seconds ago       156.8 MB
maven               3.3.9-jdk-8            a42124be49e0        2 weeks ago         652.8 MB
```

**Comment by carlossg** [comment]
It's handled in the alpine branch, will have the alpine tag soon
