### ISSUE TITLE
usage of go-offline plugin in Multi-Stage build

### ISSUE THREAD

**Issue by rcmoutinho** [carlossg/docker-maven#133]
After some research (having fun with Java code), I didn't find any issue or clear explanation about why using the offline plugin to the Multi-Stage build.

I know that going offline will avoid the usage of the Internet. But as far as I know, the initial process will need the Internet to build the image. And if you change the `pom.xml`, you lose cache and need the Internet again.

The same approach without forcing offline mode leads to the same result. But digging more in-depth on the generated images, I found out that it increases more than 200% on the layer size (from 8.2MB to 27MB, in my scenario).

Here is my research scenario about the project and the tool that I used to get this data.

Project: [basic-java-web](https://github.com/rcmoutinho/basic-java-web)
Tool: [dive](https://github.com/wagoodman/dive)

Here it is the "pure online" mode (note that I'm using the same [documentation approach](https://github.com/carlossg/docker-maven#multi-stage-builds)):

```
FROM maven:3.6-jdk-8-slim AS build

WORKDIR /usr/src/app

COPY . .
RUN mvn -B -e -T 1C verify

# - # - #

FROM tomcat:9.0-jre8-alpine AS deploy

WORKDIR $CATALINA_HOME/webapps/
COPY --from=build /usr/src/app/target/*.war ./

CMD ["catalina.sh", "run"]
```

It generates the following layers:

<img width="1550" alt="normal-mode" src="https://user-images.githubusercontent.com/11356237/68530056-81660500-02e3-11ea-8b24-229ac3b5413c.png">

Here it is the offline mode:

```
FROM maven:3.6-jdk-8-slim AS build

WORKDIR /usr/src/app

COPY pom.xml .
RUN mvn -B -e -C -T 1C org.apache.maven.plugins:maven-dependency-plugin:3.1.1:go-offline

COPY . .
RUN mvn -B -e -o -T 1C verify

# - # - #

FROM tomcat:9.0-jre8-alpine AS deploy

WORKDIR $CATALINA_HOME/webapps/
COPY --from=build /usr/src/app/target/*.war ./

CMD ["catalina.sh", "run"]
```

That generates the following layers:

<img width="1550" alt="offline-mode" src="https://user-images.githubusercontent.com/11356237/68530057-81660500-02e3-11ea-8e1d-e8a103946b26.png">

PS: To analyze the docker image, execute `dive <image_name_or_hash>`.

PSS: I executed the build of both images with the following command:

```docker build -t rcmoutinho/java-web:0.0.1 .```

---

So, after all this data.

**Is this just a matter of taste to use one or another? Or are there real scenarios that we must use a specific one?**

In the end, the final image remains the same due to the Multi-Stage build. The only difference that I noticed was the size of the build image.

Appreciate comments and explanation about it, and if I'm missing some detail in the process, or best practices to follow.

Thanks for reading and helping :)

**Comment by carlossg** [comment]
makes sense, `go-offline` would bring everything you need for multiple goals, while `verify` only brings what is needed for that goal

**Comment by rcmoutinho** [comment]
Thank you very much for the short but extremely informative answer. So for my basic scenario, there is no need to go everything offline.
