### ISSUE TITLE
Move to AdoptOpenJDK?

### ISSUE THREAD

**Issue by davidkarlsen** [carlossg/docker-maven#136]
Would it make sense to move to AdoptOpenJDK due to Oracles lack of updates and their licensing? AdoptOpenJDK is still updated and also free.

**Comment by carlossg** [comment]
we could do AdoptOpenJDK, what I'm not sure is if we want to move to AdoptOpenJDK or publish it in parallel

**Comment by davidkarlsen** [comment]
Either way is fine - I don't see a great need for both to co-exist for a long time. Basically it can be a drop-in replacement.
