### ISSUE TITLE
older bash and tar commands in jdk-13 vs jdk-11

### ISSUE THREAD

**Issue by pjungermann** [carlossg/docker-maven#137]
I'm running a build script with an assembly task and afterwards, I need to add some files outside of this command to the resulting tar file. Hereby, I was facing some issues and while investigating I found that the newer images (which was updated 2 days ago) contains older software compared to the other one which was published some time before.

maven:3.6-jdk-11 — tar: version 1.29 (2015), bash 4.4.12(1)-release (2016)
maven:3.6-jdk-13 — tar: version 1.26 (2011), bash 4.2.46(2)-release (2011)

It seems to come from openjdk:13-jdk though. openjdk:13-jdk-slim has more up-to-date ones, but is also based on debian:buster-slim. Unfortunately, there is no maven:3.6-jdk-13-slim available.

I've created an issue at openjdk, too:
https://github.com/docker-library/openjdk/issues/374

**Comment by carlossg** [comment]
this is always up to date with upstream images
