### ISSUE TITLE
When are images republished?

### ISSUE THREAD

**Issue by benze** [carlossg/docker-maven#138]
There was a bug in the base OpenJDK image that was causing ca-certificates not to be updated in the $JAVA_HOME cacerts file (https://github.com/docker-library/openjdk/issues/327).

The issue has been resolved, and a new openjdk:8-jdk image was republished to dockerhub.

When are maven images republished with the new base image?

**Comment by carlossg** [comment]
Images are continuously built by Docker
IIUC that was fixed in May so it has to be already in the maven images
