### ISSUE TITLE
3.3.9 Containers fail to run with non-root user

### ISSUE THREAD

**Issue by arthurvanduynhoven** [carlossg/docker-maven#14]
When specifying a non-root user you get an error:

`$ docker run -u 1000 -ti index.docker.io/maven:3.3.9-jdk-8 bash
touch: cannot touch ‘/root/.m2/copy_reference_file.log’: Permission denied
Can not write to /root/.m2/copy_reference_file.log. Wrong volume permissions?`

In the main README it gives example about running as a non-root user but now fails with the addition/fix of issue #11 [https://github.com/carlossg/docker-maven/commit/363ef271b86142d151f742fefa46d9d13bb656e6].

In the meantime I went back to maven:3.3.3 containers as it doesn't have this fix yet.

Thanks,

Art

**Comment by carlossg** [comment]
Just add `-e MAVEN_CONFIG=...`, I have updated the docs

**Comment by dweomer** [comment]
> Just add -e MAVEN_CONFIG=..., I have updated the docs

Is not acceptable as you have broken the ability for me to use this image within the Cloudbees Docker Pipeline plugin. See #16. I am very disappointed that this image, which used to work, has ceased to be useable within Jenkins.

**Comment by carlossg** [comment]
see https://github.com/carlossg/docker-maven/issues/16#issuecomment-303167415

> jenkinsci/docker-workflow-plugin#63 should have solved this without an image change.
