### ISSUE TITLE
Limit memory usage for maven

### ISSUE THREAD

**Issue by abialas** [carlossg/docker-maven#140]
I am trying to build my own docker image base on maven:3-jdk-11. However, I need to limit memory consumption because I need to use this docker image in the bitbucket pipeline and the whole pipe with docker cannot use more than 3GB of memory. I tried with JAVA_OPTS and MAVEN_OPTS but seems it does not work because my memory consumption is bigger than 3GB. My dockerfile looks like below:

```
FROM maven:3-jdk-11

COPY settings.xml /root/.m2/
COPY pipe.sh /

ENV JAVA_OPTS "-Xmx1g"
ENV MAVEN_OPTS "-Xmx1g"

RUN chmod 744 /pipe.sh

ENTRYPOINT ["/pipe.sh"]
```

In the pipe.sh file I just trigger:
`mvn -B verify`

**Comment by carlossg** [comment]
You probably run forked plugins that don't inherit the value
see 
https://github.com/carlossg/docker-jvm-memory
https://blog.csanchez.org/2018/06/21/running-a-jvm-in-a-container-without-getting-killed-ii/

**Comment by abialas** [comment]
I run surefire plugin so you are right - MAVEN_OPTS are not inherited. Then which value can I set to limit this?

**Comment by carlossg** [comment]
best to set surefire to not fork, or use `_JAVA_OPTIONS`
https://github.com/carlossg/docker-jvm-memory
