### ISSUE TITLE
Multiple -Xmx flags on the resulting Maven Java process

### ISSUE THREAD

**Issue by skytreader** [carlossg/docker-maven#142]
A bit related to #140 but in contrast I want Maven to use _more_ of my server's memory. I am compiling a large codebase and I keep running into `java.lang.OutOfMemoryError: GC overhead limit exceeded`.

I have set the env vars `_JAVA_OPTS`, `JAVA_OPTS`, and `MAVEN_OPTS` to my desired `-Xmx` setting but what I observed is that when the container runs, the resulting Java process has multiple `-Xmx` values:

```
/usr/lib/jvm/java-1.8-openjdk/bin/java -Xmx3g -Xmx512m -Xmx512m -classpath /usr/share/java/maven-3/boot/plexus-classworlds-2.5.2.jar ... clean verify
```

Now, I can't find documentation to back this up but it seems to me that in this case, the JVM respects the lower value (512m) which is causing my `OutOfMemoryError`s. Why is it appending multiple `-Xmx` parameters and how can I make it use my preferred value instead?

**Comment by carlossg** [comment]
The image does not set any Xmx so you need to check where are you setting them

**Comment by skytreader** [comment]
This is really odd and interesting. I'm using the `3.6-jdk-8-alpine` image as base and it seems to me that at least one of the additional dependencies I am installing is responsible for these extra `-Xmx` flags. The odd thing is none of them are directly Maven or even Java related!

My current suspicion is that it comes from glibc, installed via [sgerrand/alpine-pkg-glibc](https://github.com/sgerrand/alpine-pkg-glibc). But don't quote me on that just yet. It's just that it's the most significant binary I'm adding on top of the base image.

**Comment by carlossg** [comment]
it doesn't make sense, how are you launching the image?

**Comment by skytreader** [comment]
Well the long story is that I'm running this off Jenkins and that is where I initially observed this behavior. However I managed to reproduce this behavior via the commands in https://github.com/carlossg/docker-jvm-memory .

The experiment is:

- use the vanilla `3.6-jdk-8-alpine` image on the demos there---nothing unusual
- use the my custom base image (which bases off `3.6-jdk-8-alpine`) and the multiple `-Xmx` flags are present in the process

**Comment by skytreader** [comment]
Having more time to dig into this, it would seem I am _partially_ correct. One, or a combination, of the binaries I am installing might be responsible for the additional `-Xmx` flags. However, it is not glibc (and turns out I need it for Protobufs anyway). The binaries I removed are:

- bash
- gettext
- openrc
- procps
- curl
- wget
- python
- maven

You will notice that most of these are redundant; it even installs maven! This Dockerfile was only handed down to me so I'm not sure why these installs were there in the first place :frowning_face: .

My problem is solved for all intents and purposes so I'm closing this issue now.
