### ISSUE TITLE
Issue line 26 docker file

### ISSUE THREAD

**Issue by madagama89** [carlossg/docker-maven#145]
I am execute of the docker file, but when run line 26, the execution show following message "**Invoke-WebRequest: No such host is known**" and fail the creation image. What is the problem ?

Thanks.

**Comment by carlossg** [comment]
what command do you run

**Comment by thesame00** [comment]
in docker-maven/openjdk-14 execute docker build . -t latest
Sending build context to Docker daemon  6.144kB
Step 1/12 : FROM openjdk:14-jdk
14-jdk: Pulling from library/openjdk
83755823a002: Already exists 
c0e105caaf23: Already exists 
2fb07d19f2c1: Already exists 
Digest: sha256:87e0916df91b8d558aede4502f9229b9b58dfab71d613d69a77403744a48a02d
Status: Downloaded newer image for openjdk:14-jdk
 ---> db8922a53903
Step 2/12 : ARG MAVEN_VERSION=3.6.3
 ---> Running in 540204d7c73e
Removing intermediate container 540204d7c73e
 ---> cafadaae8900
Step 3/12 : ARG USER_HOME_DIR="/root"
 ---> Running in 9504258a0c3d
Removing intermediate container 9504258a0c3d
 ---> e73b91923316
Step 4/12 : ARG SHA=c35a1803a6e70a126e80b2b3ae33eed961f83ed74d18fcd16909b2d44d7dada3203f1ffe726c17ef8dcca2dcaa9fca676987befeadc9b9f759967a8cb77181c0
 ---> Running in 4f5b9ca95e1b
Removing intermediate container 4f5b9ca95e1b
 ---> 71b92c64bf72
Step 5/12 : ARG BASE_URL=https://apache.osuosl.org/maven/maven-3/${MAVEN_VERSION}/binaries
 ---> Running in 7e1aaa766f24
Removing intermediate container 7e1aaa766f24
 ---> eefe170e642c
Step 6/12 : RUN mkdir -p /usr/share/maven /usr/share/maven/ref   && curl -fsSL -o /tmp/apache-maven.tar.gz ${BASE_URL}/apache-maven-${MAVEN_VERSION}-bin.tar.gz   && echo "${SHA}  /tmp/apache-maven.tar.gz" | sha512sum -c -   && tar -xzf /tmp/apache-maven.tar.gz -C /usr/share/maven --strip-components=1   && rm -f /tmp/apache-maven.tar.gz   && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn
 ---> Running in 9e444d3fb8b0
curl: (6) Could not resolve host: apache.osuosl.org; Unknown error
The command '/bin/sh -c mkdir -p /usr/share/maven /usr/share/maven/ref   && curl -fsSL -o /tmp/apache-maven.tar.gz ${BASE_URL}/apache-maven-${MAVEN_VERSION}-bin.tar.gz   && echo "${SHA}  /tmp/apache-maven.tar.gz" | sha512sum -c -   && tar -xzf /tmp/apache-maven.tar.gz -C /usr/share/maven --strip-components=1   && rm -f /tmp/apache-maven.tar.gz   && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn' returned a non-zero code: 6

**Comment by carlossg** [comment]
some temporary or dns error `Could not resolve host: apache.osuosl.org; Unknown error`
but you don't need to build the image, it is already built in dockerhub
