### ISSUE TITLE
Using docker-maven in Drone CI

### ISSUE THREAD

**Issue by dcerecedo** [carlossg/docker-maven#15]
I' trying to use docker-maven as part of a Drone CI implementation. I have extended the docker-maven `Dockerfile` with mine, adding custom `settings.xml`:

My `Dockerfile`:
```
FROM maven:3-jdk-8

COPY settings.xml /usr/share/maven/ref/
```

My `settings.xml`:
```

<settings>
    <localRepository>/usr/share/maven/ref/repository</localRepository>
    <servers>
	<server>
		<id>${env.NEXUS_ID}</id>
		<username>${env.NEXUS_USERNAME}</username>
		<password>${env.NEXUS_PASSWORD}</password>
	</server>
    </servers>
    <pluginGroups>
        <pluginGroup>org.sonarsource.scanner.maven</pluginGroup>
    </pluginGroups>
    <profiles>
        <profile>
            <id>sonar</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <properties>
                <sonar.host.url>${env.SONAR_URL}</sonar.host.url>
            </properties>
        </profile>
     </profiles>
</settings>
```
The drone build is configured to use this custom image. I use docker environment variables to parameterize the maven settings. When the drone build starts, the first thing I do is check that the environment variables are right and the `settings.xml` file has been copied to the `/usr/share/maven/ref/` folder. Everything seems ok.

Nevertheless, the build fails to execute an `mvn clean deploy` as it cannot deploy the resulting jar to my private nexus server.

When I execute the build manually in my local system with the same `settings.xml` and the same environment variables everything works fine. I have run out of ideas on how to determine if the problem is with the image or with other component. Any ideas?

Thanks for the great image and for your support!

**Comment by carlossg** [comment]
what error do you get? 401? 403? ...

**Comment by dcerecedo** [comment]
401 unauthorized. But credentials are ok in the env variables.

When I execute the image in standalone (without drone) through the command line:

`docker run -ti -e SONAR_URL=http://localhost:9000 -e NEXUS_ID=server-id -e NEXUS_USERNAME=user -e NEXUS_PASSWORD=pass -v /source:/usr/src byteflair/docker-maven-private bash`

And within the image, I run the `mvn clean deploy` everything works fine. Blame on drone?

**Comment by carlossg** [comment]
yep, if that works in your docker then I have no idea what they do

maybe https certs or something

**Comment by dcerecedo** [comment]
I'm using Let's encrypt from IdenTrustCA. They are in the Java Key Store since 8u101. This image is on 8u102. And in any case the manual execution from within the container is working.

Thanks in any case! If I make it work and is relevant to your image I'll drop you a line. I close this issue.
