### ISSUE TITLE
apt-get command not found in latest maven version 

### ISSUE THREAD

**Issue by dheeraj29006** [carlossg/docker-maven#151]
it was working a month ago but not now giving "command not found"

**Comment by seonggwonyoon** [comment]
If you are using the latest version, you can use yum.

**Comment by carlossg** [comment]
latest tag has switched to openjdk-14 as the official `openjdk` tag has
if you need specific tag you should not use `latest`

**Comment by lightswitch05** [comment]
I had this issue too on `'maven:3.6-openjdk-14'` which suddenly switched to oracle linux. Changing to `maven:3.6-adoptopenjdk-14` will give you a Debian. base back

**Comment by hannibal218bc** [comment]
With `3.8.1-*-17` the `adoptopenjdk`-image features neither `apt` nor `yum` or `zypper` (I have no experience with Oracle Linux and no intentions to gather them); but the `3.8.1-openjdk-17-slim` image is still based on Ubuntu and has `apt` available.
