### ISSUE TITLE
Not able to pull Zulu JDK images

### ISSUE THREAD

**Issue by dbelyaev** [carlossg/docker-maven#152]
Hello I have tried to pull different versions of Maven + Zulu JDK docker images by using those commands:
```
docker pull maven:azulzulu-11
docker pull maven:3.6.3-azulzulu-11
docker pull maven:3.6-azulzulu-11
docker pull maven:3-azulzulu-11
```
As a result I am always getting:
`Error response from daemon: manifest for <tag-listed-above-here> not found: manifest unknown: manifest unknown`

Neither can I find anything with `azul` or `zulu` searching on [official Maven docker repo](https://hub.docker.com/_/maven).

I see that there is Dockerfile to build azulzulu docker image in repository: https://github.com/carlossg/docker-maven/blob/master/azulzulu-11/Dockerfile

And [log from GitHub actions run](https://github.com/carlossg/docker-maven/runs/531255383?check_suite_focus=true) (see step `build` and lines **5194-5196**, for example) shows that it is building and pushing Docker images to docker.io.

Can anyone help me with this issue?

**Comment by carlossg** [comment]
that's only under `csanchez/maven:azulzulu-11` because there is no zulu official image
