### ISSUE TITLE
Python 2.7 was retire in 2020

### ISSUE THREAD

**Issue by junior-rassystem** [carlossg/docker-maven#164]
Upgrade to Python 3.

DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support

**Comment by carlossg** [comment]
python is included from parent images, when those update, the maven one will update
