### ISSUE TITLE
[mvn:3] mvn-entrypoint.sh: line 24: find: command not found

### ISSUE THREAD

**Issue by Song2017** [carlossg/docker-maven#169]
### Command
    - export run_maven="docker run -i --rm   -v $PWD:$PWD -w $PWD maven:3 "
    - sh -c "$run_maven mvn clean compile assembly:single -Dmaven.test.skip=true"

`Digest: sha256:a98aae6e78597d733a5aadcf165e6d881005db3a6b4d635d0764322ffd5d3da7` works well, `ddccf1eee241efa1f7b4a9514c13cf53b43842d7bd25ec662f231d1efcaca1dc ` failed
### Error message:
```
Digest: sha256:ddccf1eee241efa1f7b4a9514c13cf53b43842d7bd25ec662f231d1efcaca1dc
Status: Downloaded newer image for maven:3
/usr/local/bin/mvn-entrypoint.sh: line 24: find: command not found
```

**Comment by kakawait** [comment]
Maybe dups of #165
