### ISSUE TITLE
Not usable under non-root user

### ISSUE THREAD

**Issue by dimitriyremerov** [carlossg/docker-maven#17]
Due to `ARG USER_HOME_DIR="/root"` it's not possible to start any processes under a different user.

```
$ docker run -it --rm -u $(id -u):$(id -g) maven bash
touch: cannot touch ‘/root/.m2/copy_reference_file.log’: Permission denied
Can not write to /root/.m2/copy_reference_file.log. Wrong volume permissions?
```

**Comment by carlossg** [comment]
have you read the instructions https://github.com/carlossg/docker-maven#running-as-non-root ?

**Comment by dimitriyremerov** [comment]
Oh sorry, my bad. Missed it in the manual for some reason.

**Comment by spazm** [comment]
The running-as-non-root instructions should specify that the `MAVEN_CONFIG` env must point to a directory writable by the mapped user.  Even when running a command other than `mvn`.  This information is included implicitly by the example command, but it is not clear why the -e is needed when running any command other than mvn.  (e.g. OP was trying to run bash)


> Maven needs the user home to download artifacts to, and if the user does not exist in the image an extra `user.home` Java property needs to be set.

Perhaps something like:
> On run, the maven image copies files into the maven config directory.  [See packaging a local repository with the image].  
> Maven config directory defaults to `/root/.m2`. The image will fail to run if this directory is not writable by the user. 
> Override the default location of `/root/.m2` by setting `MAVEN_CONFIG` environment variable to a directory writable by the non-root user.
