### ISSUE TITLE
pulling image from docker hub stucked 

### ISSUE THREAD

**Issue by slim-hmidi** [carlossg/docker-maven#170]
i'm using `maven:3.6.3-jdk-11-slim` and I tried to build my image using it but it freezes in the first step:
```
Step 1/19 : FROM maven:3.6.3-jdk-11-slim as dependencies
3.6.3-jdk-11-slim: Pulling from library/maven
bf5952930446: Pull complete
092c9b8e633f: Pull complete
0b793152b850: Pull complete
7900923f09cb: Waiting
538f67ffe923: Download complete
4259c181cc3f: Download complete
6dcd7f2876f0: Download complete
4d36d6675b06: Download complete

```

Tried many time and always there is a problem with ` 7900923f09cb `, it is not possible to download or pull image.

**Comment by carlossg** [comment]
must be a temporary or client error I just downloaded it today

**Comment by slim-hmidi** [comment]
I will check it again later.
