### ISSUE TITLE
git error with maven:3.6.3 image

### ISSUE THREAD

**Issue by Gioxi** [carlossg/docker-maven#174]
Hi,
I use the maven:3.6.3 docker image for building with Jenkins. I'm junior in docker usage.
Here is my Jenkinsfile
pipeline {
  agent {
    docker {
      image 'maven:3.6.3'
    }
  }
  stages {
    stage('mvn build') {
      steps {
        script {
           sh "git clone git_address"
           sh "mvn deploy"
        }
      }
    }
  }
}

I need the git command to retrieve additional files for the build, coming from another project.
All worked as a charm until it started to break in august 2020 with the following error message
script.sh: line 1: git: command not found

My understanding is that the maven image stopped to have git installed, why?
I tried to fix it by modifying my Jenkinsfile to add git installation but couldn't find a solution.

Thanks for any help.

**Comment by nadnoslen** [comment]
Hey @Gioxi,

Back on August 27 some of our Maven builds in our Azure devops-world faced a similar problem.

For us, the `useradd` command was no longer found.  I am wondering if these images were thinned out intentionally by the maintainers?

As a quick solution to get all of our builds working again, we referred to the previous _working_ image; in our case the configuration changed like this:

```yaml
# container: maven:3-openjdk-14
 # August 2020 changes to the maven:3-openjdk-14 container prevents a `useradd` operation from completing
 # pointing to previous working container temporarily...
 container: maven@sha256:a98aae6e78597d733a5aadcf165e6d881005db3a6b4d635d0764322ffd5d3da7 
```

So in your case, you might be able to update your `image` string of `maven:3.6.3` to a previous container version?  It's worth a shot, take a look in your Jenkins logs for the last image that was working?  That might get you going while maintainers work on this issue.  Good luck.

**Comment by Gioxi** [comment]
Thanks a lot @nadnoslen for your reply.
I'm quite surprised that an image is modified keeping the same version number but loosing compatibility, my understanding is that this is not really the right way to do, but I'm maybe wrong.
Anyway, version 3.6.3-openjdk-14 had the same problem, but 3.6.3-openjdk-11 fixed it.
This looks like a workaround to me, the real solution would be to add git to the image at the beginning of the build.
Do you have an idea about which command I should execute to add git to these images? I tried with apk and yum but they didn't worked.

**Comment by carlossg** [comment]
official images are rebuild by Docker inc. when base images change. You should lock to a specific sha

to install software use `microdnf` https://github.com/carlossg/docker-maven/blob/master/openjdk-14/Dockerfile#L8

**Comment by Gioxi** [comment]
Thanks a lot, I'll try it.

**Comment by neon-dev** [comment]
@carlossg could you please add git to the images? I'd argue it's a common usecase to use your image for cloning and building Java projects. Also plugins like the buildnumber-maven-plugin depend on the VCS client being installed. `microdnf install git` is possible of course but consumes build minutes unnecessarily.

**Comment by carlossg** [comment]
I've looked at it and adds substantial size to the images due to the git dependencies. 
It could be added to those where size does not increase too much or add new tags

**Comment by neon-dev** [comment]
Aren't the *-slim and *-alpine images the only ones that should be excluded?
