### ISSUE TITLE
 3.6.3-jdk-8-alpine is missing

### ISSUE THREAD

**Issue by angeldelblanco** [carlossg/docker-maven#178]
I was trying to increase mvn version from 3.6.1 to 3.6.3 to solve a problem related to a " Connection reset" that appeared randomly, but I can not find tag maven:3.6.3-ibmjava-8-alpine.

Are you planning to generate it?

Thx in advance

**Comment by carlossg** [comment]
it is there https://hub.docker.com/layers/maven/library/maven/3.6.3-ibmjava-8-alpine/images/sha256-77af163bb0083bbfb9865653a4a4bdc595e85c4d39fa1d44c0bb985f76a29c0f?context=explore

**Comment by angeldelblanco** [comment]
My bad, I wrote right in the tittle, but wrong in the body.

The version I was looking for is 3.6.3-jdk-8-alpine.

Sorry for the mistake.

**Comment by carlossg** [comment]
it is no longer supported upstream 6251fd3dfc1a3ec50c7c38a112acc5d6b3579dc5
