### ISSUE TITLE
New images (I think >= 15 but may start with 14) don't have full package manager

### ISSUE THREAD

**Issue by omnipitous** [carlossg/docker-maven#181]
The new base image used for at least 15 no longer includes YUM (or even the full new DNF) ... microdnf (included) can install a very small number of things and this deprecation breaks SOOOO many Dockerfiles in the ecosystem.

I'm sure some appreciate the significantly smaller image with this but for those of us who need a beefier image it would be greatly useful to have maven images that are built on "less-slim" base os images. Thanks!

**Comment by carlossg** [comment]
that's because the upstream {{openjdk}} images switched to oracle linux, I guess we could have some extending {{openjdk:jdk-slim-buster}}
