### ISSUE TITLE
Cache m2 dependencies for subsequent builds

### ISSUE THREAD

**Issue by cyberjoac** [carlossg/docker-maven#19]
Hi,

Thanks for this great docker image ! 
Is it possible to cache already downloaded m2 dependencies so that next time build happens, it doesn't download once again all dependencies ? 
Thanks

**Comment by carlossg** [comment]
https://github.com/carlossg/docker-maven#packaging-a-local-repository-with-the-image

**Comment by cyberjoac** [comment]
Thanks :-)
