### ISSUE TITLE
Text errors in https://hub.docker.com/_/maven

### ISSUE THREAD

**Issue by xiyoukeji-cdd** [carlossg/docker-maven#192]
In the web:
> Reusing the Maven local repository
> The local Maven repository can be reused across containers by creating a volume and mounting it in /root/.m2.
> $ docker volume create --name maven-repo
> $ docker run -it -v maven-repo:/root/.m2 maven mvn archetype:generate # will download artifacts
> $ docker run -it -v maven-repo:/root/.m2 maven mvn archetype:generate # will reuse downloaded artifacts

In face, if someone want to reuse the Maven local repository he should mount /usr/share/maven/ref/repository instead of /root/.m2
Because in settings-docker.xml:
`<localRepository>/usr/share/maven/ref/repository</localRepository>`

So 法克鱿 lazy author

**Comment by snuglove** [comment]
you shit  懂?

**Comment by carlossg** [comment]
actually... you are wrong
`settings-docker.xml` is not used by default, only when passing `-s`

**Comment by xiyoukeji-repos** [comment]
Why doesn't author have a try?
In docker it use settings-docker.xml by default
QAQ

**Comment by nomagick** [comment]
That's not how opensource work. @xiyoukeji-cdd @xiyoukeji-repos 

If you don't like it, fork it , change it , then PR your change.
