### ISSUE TITLE
Unable to run any package manager on maven:3.6.3-openjdk-15

### ISSUE THREAD

**Issue by andreamisu** [carlossg/docker-maven#195]
Currently using maven:3.6.3-openjdk-15 to deploy a set of Springboot application on a CD/CI Gitlab chain.

Even though I wondered that 3.6.3-openjdk-15 was based on Alpine, no package manager (apk , apt-get, yum, ..) seems to work really.

Is this how it was implemented? if yes, there's a solution to enabling packages installing?

**Comment by carlossg** [comment]
openjdk is using oraclelinux where you can use  `microdnf install`
