### ISSUE TITLE
None of the images work on the Raspberry Pi 4 

### ISSUE THREAD

**Issue by slavking** [carlossg/docker-maven#199]
Using https://hub.docker.com/r/arm32v7/maven on stock Raspberry Pi 4.
I will provide the details of the software configuration and the error message in a separate post.

**Comment by carlossg** [comment]
`latest` is not available in arm32v7, you'd need to use some of the adoptopenjdk images 
https://github.com/docker-library/official-images/blob/master/library/maven

**Comment by carlossg** [comment]
can you check if you can run `adoptopenjdk:15-jdk-hotspot` ? if that doesn't work either then it is an issue with the adoptopenjdk image that we extend

For the permissions you can try this to see the permissions

```
docker run -it --rm --name my-maven-project \
 -v /root/maven \
 -e MAVEN_CONFIG=/root/maven \
 maven:adoptopenjdk sh -c "id && ls -laF /root/maven"
```

**Comment by slavking** [comment]
Here's the output:
```
root@raspberrypi:~# docker run -it --rm --name my-maven-project \
>  -v /root/maven \
>  -e MAVEN_CONFIG=/root/maven \
>  maven:adoptopenjdk sh -c "id && ls -laF /root/maven"
Can not write to /root/maven/copy_reference_file.log. Wrong volume permissions? Carrying on ...
uid=0(root) gid=0(root) groups=0(root)
total 12
drwxr-xr-x 3 root root 4096 Mar  9  2021 ./
drwx------ 1 root root 4096 Mar  9  2021 ../
-rw-r--r-- 1 root root    0 Mar  9  2021 copy_reference_file.log
drwxr-xr-x 2 root root 4096 Mar  9  2021 repository/
```

**Comment by carlossg** [comment]
The first one works for me

```
docker run -it --rm --name my-maven-project \
  -v /root/maven \
  -e MAVEN_CONFIG=/root/maven \
  maven:adoptopenjdk sh -c "id && ls -laF /root/maven"
uid=0(root) gid=0(root) groups=0(root)
total 20
drwxr-xr-x 3 root root 4096 Mar  9 18:23 ./
drwx------ 1 root root 4096 Mar  9 18:23 ../
-rw-r--r-- 1 root root  136 Mar  9 18:23 copy_reference_file.log
drwxr-xr-x 2 root root 4096 Mar  9 18:23 repository/
-rw-r--r-- 1 root root  327 Mar  9 18:23 settings-docker.xml
```


For the second one try this 

```
docker run -it --rm --name my-maven-project -v /root/maven -e MAVEN_CONFIG=/root/maven adoptopenjdk:15-jdk-hotspot java -version
```

**Comment by carlossg** [comment]
you still get the `No monotonic clock was available` message. 

About the permission error there must be something on your machine on how the volumes get mounted in docker

**Comment by slavking** [comment]
I think I have found the solution:
https://stackoverflow.com/questions/65717411/operation-not-permitted-during-docker-build

Thank you for your assistance and help! Since the issue is on my side, I will close this ticket once I have 100% verified the fix.

**Comment by slavking** [comment]
It works, but now I have a JVM issue. It seems that Its only safe to run Java 11 on the Arm V7.
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGBUS (0x7) at pc=0xb3e92a84, pid=17, tid=36
#
# JRE version: OpenJDK Runtime Environment AdoptOpenJDK (14.0.2+12) (build 14.0.2+12)
# Java VM: OpenJDK Server VM AdoptOpenJDK (14.0.2+12, mixed mode, sharing, g1 gc, linux-arm)
# Problematic frame:
# v  ~StubRoutines::atomic_load_long
#

```
