### ISSUE TITLE
How to avoid download of jar deps at every image building

### ISSUE THREAD

**Issue by bitliner** [carlossg/docker-maven#2]
Every time the code of java classes in my maven project changes, building an image requires to download again all the java dependencies from maven repositories.

I am trying to avoid that using a data volume, specifically I run `docker run -v "$(pwd)":/root/.m2` but of course this command is not about building an image, so it does not help. 

Docker does not support data volumes when you build an image.

Is there any other way you suggest to speed up the image building process avoiding the download of all the java dependencies?

**Comment by carlossg** [comment]
Just create new images extending this one that run maven to download the dependencies. The layers will be cached

**Comment by bitliner** [comment]
My actual Dockerfile now it is only 2 lines:

```
FROM maven:3.2-jdk-7-onbuild
CMD ["java","-jar","SentenceSplitterHttpServer.jar","6002"]
```

You mean: remove *onbuild* hook and run your own maven commands?

**Comment by carlossg** [comment]
That should cache the intermediate images if you don't delete them after a build. Otherwise just create another image with the stuff you want that doesn't change

**Comment by xenoterracide** [comment]
data volume would be awesome, so if I have 2 projects which have the same dependencies...

**Comment by carlossg** [comment]
you can mount a volume in /root/.m2

**Comment by xenoterracide** [comment]
Is that documented? I thought the dockerfile had to define where volumes could be mounted... maybe used to be the case... unsure.

 wait... is mvn running as root on this? maven and java really shouldn't be run as root even in the container. https://docs.docker.com/reference/builder/#user

**Comment by carlossg** [comment]
> is that documented in the maven docs? I thought the dockerfile had to define where volumes could be mounted... maybe used to be the case... unsure.

no, just use `docker -v`

> wait... is mvn running as root on this? maven and java really shouldn't be run as root even in the container. https://docs.docker.com/reference/builder/#user

use `docker --user`

**Comment by xenoterracide** [comment]
sadly in some environments I don't actually have access to the docker cli, which means I can't set either of those.

**Comment by carlossg** [comment]
so how do you start containers?? those are docker API options too

**Comment by xenoterracide** [comment]
wercker (continous integration) starts it for me, but doesn't really expose command line options.

Honestly overriding is still an option I could make a Dockerfile, but it would seem better to use the secure option (not running as root) first and make people force access to root if they really needed it. Especially since I would never have even thought to check that, and the Dockerfile isn't proudly displayed on the docker site, so you have to dig for it.

**Comment by carlossg** [comment]
the recommended way for official images in "tooling" is to use root 
https://github.com/docker-library/official-images/pull/690#issuecomment-97490517

**Comment by dodwyer** [comment]
mounting /root/.m2 solved this for me.

**Comment by carlossg** [comment]
The readme now explains how to build images with a cached repo
