### ISSUE TITLE
Permission denied running openjdk:8-jdk-alpine

### ISSUE THREAD

**Issue by bat26** [carlossg/docker-maven#20]
Using this Dockerfile :
https://github.com/carlossg/docker-maven/blob/322d0dff5d0531ccaf47bf49338cb3e294fd66c8/jdk-8/Dockerfile

```
FROM openjdk:8-jdk-alpine

RUN apk add --no-cache curl tar bash

ARG MAVEN_VERSION=3.3.9
ARG USER_HOME_DIR="/root"

RUN mkdir -p /usr/share/maven /usr/share/maven/ref \
  && curl -fsSL http://apache.osuosl.org/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz \
    | tar -xzC /usr/share/maven --strip-components=1 \
  && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn

ENV MAVEN_HOME /usr/share/maven
ENV MAVEN_CONFIG "$USER_HOME_DIR/.m2"

COPY mvn-entrypoint.sh /usr/local/bin/mvn-entrypoint.sh
COPY settings-docker.xml /usr/share/maven/ref/

VOLUME "$USER_HOME_DIR/.m2"

ENTRYPOINT ["/usr/local/bin/mvn-entrypoint.sh"]
CMD ["mvn"]
```

Gives the following output

> 
>  sudo docker run maven-docker
> docker: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"/usr/local/bin/mvn-entrypoint.sh\\\": permission denied\"\n".
> 

Any ideas how to fix?

**Comment by carlossg** [comment]
You don't have the right permissions (exec) in mvn-entrypoint.sh

**Comment by JSXFEDU** [comment]
you cloud clone this git repo and run
`chmod +x mvn-entrypoint.sh`
to give this file right permission.
and build docker image.
