### ISSUE TITLE
Alpine images for JDK 15

### ISSUE THREAD

**Issue by AvaPL** [carlossg/docker-maven#200]
It seems that there are no Alpine images for JDK 15. It would be nice to include them as slim versions aren't that slim as Alpine ones.

**Comment by carlossg** [comment]
there are no alpine images for the upstream JDKs
not for openjdk nor adoptopenjdk
https://github.com/docker-library/official-images/blob/master/library/openjdk
https://github.com/docker-library/official-images/blob/master/library/adoptopenjdk

**Comment by AvaPL** [comment]
I didn't know the way in which Alpine images are published to Docker. Now it's clear for me why there are no Alpine Maven images. If anybody reading this issue needs explanation, then here it is: https://github.com/docker-library/openjdk/pull/235#issuecomment-424599754
