### ISSUE TITLE
Remove word 'official'

### ISSUE THREAD

**Issue by michael-o** [carlossg/docker-maven#202]
Your project uses the term *official* w/o making it clear that these images are *not* provided by the Apache Maven team. Please add a clear statement that these are community images.

I don't know whether you are responsible for https://hub.docker.com/_/maven?tab=description&page=1&ordering=last_updated too, but is contains the same information and even worse:
> Maintained by: the Maven Project

This is obviously wrong and links to this GitHub project.

Remove the false information please. I am an Apache Maven PMC member and lead developer.

**Comment by olamy** [comment]
haha life is endless loop finally you keep uploading maven stuff somewhere ;)

**Comment by carlossg** [comment]
ok, docker-library/docs#1900 addressed
