### ISSUE TITLE
Not able to use maven:3-openjdk-8-nanoserver-1809 as Base Image

### ISSUE THREAD

**Issue by lokeshChinta** [carlossg/docker-maven#203]
My AIM is run the Selenium webdriver Automation scripts using Docker  Maven windows Image 

Below are the contents of my Dockerfile

FROM maven:3-openjdk-8-nanoserver-1809

WORKDIR /app

COPY ./selenium-server-standalone-3.141.59.jar  ./

COPY ./ChromeSetup.exe  ./

COPY ./chromedriver.exe ./

RUN .\ChromeSetup.exe /silent/install

EXPOSE 4444

CMD ["java -jar ./selenium-server-standalone-3.141.59.jar]

COPY ./ 			           ./

ENTRYPOINT mvn verify

use the command : docker build -t "<username/imageName>" . to build the image 

The above command displayed the below error in CMD

Sending build context to Docker daemon  355.8MB
Step 1/10 : FROM maven:3-openjdk-8-nanoserver-1809
manifest for maven:3-openjdk-8-nanoserver-1809 not found: manifest unknown: manifest unknown

please help

**Comment by carlossg** [comment]
that tag does not exist, you have the tag list at https://github.com/carlossg/docker-maven
