### ISSUE TITLE
/usr/share/maven/ref/settings.xml not copied to $MAVEN_CONFIG/settings.xml

### ISSUE THREAD

**Issue by rhbecker** [carlossg/docker-maven#208]
I can't tell whether I'm misunderstanding the instructions or if this is a bug ...

Per the [Packaging a local repository with the image](https://github.com/carlossg/docker-maven#packaging-a-local-repository-with-the-image) section of the `README.md`, I've added the following to my `Dockerfile` ...

```
COPY settings.xml /usr/share/maven/ref/
```

Having done so, should I expect my local `settings.xml` file to then be copied on container startup to `$MAVEN_CONFIG`?

I'm using `maven:3.8.1-amazoncorretto-11`.
I've confirmed that `$MAVEN_CONFIG` is defined as `/root/.m2`.
When I list the contents of `/root/.m2`, it only contains a `repository` sub-directory; my `settings.xml` file is NOT present.

I was expecting that I'd be able to execute `mvn deploy` without specifying a custom path to `settings.xml`. Certainly, it works to execute it as `mvn -s /usr/share/maven/ref/settings.xml deploy`, but I'm hoping to confirm whether that's necessary and intended.

**Comment by carlossg** [comment]
it works, unless you override the  entrypoint/cmd

```
docker run -ti --rm test bash -c "MAVEN_CONFIG=/root/.m2 /usr/local/bin/mvn-entrypoint.sh && cat /root/.m2/settings.xml"
<settings xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
</settings>%
```

**Comment by rhbecker** [comment]
I confirmed that the `ENTRYPOINT` script works as described when running locally. The problem is that I'm using the image as a [custom build environment](https://support.atlassian.com/bitbucket-cloud/docs/use-docker-images-as-build-environments/#Custom-build-environments), with Bitbucket Pipelines, and I just learned that [apparently](https://community.atlassian.com/t5/Answers-Developer-Questions/Run-custom-entrypoint-command-in-Pipelines/qaq-p/516534#M54190) Pipelines overwrites `ENTRYPOINT`.

Thanks for your response. I'll close the issue now, but if you are familiar with Pipelines and have any recommendations on the optimal work-around, please let me know.
