### ISSUE TITLE
Alpine images for OpenJDK 17

### ISSUE THREAD

**Issue by dineiar** [carlossg/docker-maven#212]
This issue is very similar to #200, which asks for images based on JDK 15 and was deemed unfeasible because there were no OpenJDK nor AdoptOpenJDK images for JDK 15.

I checked in the link posted in that issue (https://github.com/docker-library/official-images/blob/master/library/openjdk) that there are images available for OpenJDK 17 now, so I'm asking for a maven image based in that version (tag `17-jdk-alpine`). The Dockerfile can be found here: https://github.com/docker-library/openjdk/blob/master/17/jdk/alpine3.13/Dockerfile

**Comment by maffe** [comment]
Added in commit 70981755895616b08e0718e3f0dd7e8fa4de4f6c
