### ISSUE TITLE
Add support for ARM32v7?

### ISSUE THREAD

**Issue by budney** [carlossg/docker-maven#215]
I created a fork of your repo so I could build images that work on arm32v7, which I did by replacing your base images with arm32v7/adoptopenjdk:<<version-number>> for version in {8, 11, 15, 16}. This only works for the adoptopenjdk images, obviously.

I don't have the docker-fu to tell docker build to use these images for ARM, and your images for everything else, and I was hesitant to create yet more directories like arm32-adoptopenjdk-11, etc.

Thanks!

**Comment by carlossg** [comment]
the images in docker hub already support arm32v7

https://github.com/docker-library/official-images/blob/master/library/maven#L94-L97

**Comment by budney** [comment]
Thanks! OK, that's super weird: I tried repeatedly to pull one of your images, and kept being told that there were none matching my architecture. Must be I didn't use quite the right tags.
