### ISSUE TITLE
Consider adding a Dockerfile that doesn't declare the .m2 directory as a volume

### ISSUE THREAD

**Issue by aslo** [carlossg/docker-maven#24]
Child images are unable to remove the VOLUME declaration for this directory, and this means that pre-cached maven artifacts need to be copied into this directory at container start time. 

When many artifacts are cached, this can take a long time, and it's on the critical path of performing a maven build with this container. It would be nice to be able to just pre-download artifacts directly into the .m2/repository directory.

**Comment by carlossg** [comment]
That was discussed in https://github.com/carlossg/docker-maven/issues/11

You can use `-Duser.home=` to point to another dir

**Comment by aslo** [comment]
Ok, that's a reasonable solution. Thanks!
