### ISSUE TITLE
maven:3.8.4-openjdk-17 suddenly throwing permission error

### ISSUE THREAD

**Issue by michaelpitts-framework** [carlossg/docker-maven#241]
Here is an excerpt from my Dockerfile:

```
## Build Stage
FROM maven:3.8.4-openjdk-17 as BUILD
ENV APP_HOME=/usr/src/app
RUN mvn --version
```

when `mvn --version` runs, the following error occurs:

```
Step 4/35 : RUN mvn --version
--
113 | ---> Running in 1b9ccafcd0e7
114 | ls: cannot access '/usr/bin/mvn': Operation not permitted
115 | Error: Could not find or load main class org.codehaus.plexus.classworlds.launcher.Launcher
116 | Caused by: java.lang.ClassNotFoundException: org.codehaus.plexus.classworlds.launcher.Launcher
117 | The command '/bin/sh -c mvn --version' returned a non-zero code: 1
```

Our Dockerfile has not changed for some time, I just upgraded from 3.8.3 to 3.8.4 to see if that would solve this issue, it didn't. Any ideas what may be causing this? Our development team is using these maven images for the build steps in our CI/CD automation so this is greatly impairing our system.

**Comment by carlossg** [comment]
works here on Mac, and nothing has changed other than the version lately

```
docker run -ti --rm maven:3.8.4-openjdk-17 mvn --version
Unable to find image 'maven:3.8.4-openjdk-17' locally
3.8.4-openjdk-17: Pulling from library/maven
28587b6e6475: Pull complete
b1655352c888: Pull complete
1f9646f00e96: Pull complete
5fbbe72f07bf: Pull complete
c650f8fba229: Pull complete
df43a896e3bf: Pull complete
0e00685a0ec7: Pull complete
Digest: sha256:0e09a20f8bd3bd9f1c96ba531c3d410e3501fa319b3799479710adfbf6a495ae
Status: Downloaded newer image for maven:3.8.4-openjdk-17
Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)
Maven home: /usr/share/maven
Java version: 17.0.1, vendor: Oracle Corporation, runtime: /usr/java/openjdk-17
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "5.10.47-linuxkit", arch: "amd64", family: "unix"
```

**Comment by carlossg** [comment]
The base image may have changed though, this inherits `openjdk:17-jdk-oraclelinux8` which is a moving tag

https://github.com/carlossg/docker-maven/blob/master/openjdk-17/Dockerfile#L1

**Comment by michaelpitts-framework** [comment]
@carlossg thank you. I cannot reproduce it on my mac either. I set up a quick Ubuntu 18 VM and installed the appropriate version of docker (our build image on AWS is aws/codebuild/docker:18.09.0) and still couldn't reproduce the issue. 

It looks like the last commit to the base image was 5 days ago, this would line up with when our issue started occurring. Is there a way you recommend we can workaround that change and use the older base image?

**Comment by carlossg** [comment]
You should use the image sha instead of the tag if you want reproducible builds. 
Check the issues, there have been similar ones in the past, old docker versions, different architectures,...

**Comment by sermo-de-arboribus** [comment]
I have the same problem as michaelpitts-framework and am baffled about my observations, because the behaviour is different for the same image digest on different machines. Always using `sha256:0e09a20f8bd3bd9f1c96ba531c3d410e3501fa319b3799479710adfbf6a495ae`, I get the following results:

On an Ubuntu 18.04.2 LTS in WSL host with docker 18.09.7 I get the following output:
```
pagina@pt-804:/mnt/c/WINDOWS/system32$ docker run --name maven-test --rm -i -t maven:3.8.4-openjdk-17 mvn --version
Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)
Maven home: /usr/share/maven
Java version: 17.0.1, vendor: Oracle Corporation, runtime: /usr/java/openjdk-17
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "5.10.60.1-microsoft-standard-wsl2", arch: "amd64", family: "unix"
```

On an Ubuntu 18.04.5 LTS VM with docker 17.05.0-ce host I get the following output:
```
root@zelos:~# docker run --name maven-test --rm -i -t maven:3.8.4-openjdk-17 mvn --version
ls: cannot access '/usr/bin/mvn': Operation not permitted
Error: Could not find or load main class org.codehaus.plexus.classworlds.launcher.Launcher
Caused by: java.lang.ClassNotFoundException: org.codehaus.plexus.classworlds.launcher.Launcher
```

So just making sure to use a working image digest may not be enough, one might have to take docker and possibly even OS versions into account.

**Comment by sermo-de-arboribus** [comment]
Just upgraded my VM's docker version from 17.05.0-ce to 20.10.11 and can confirm that this solves the problem

**Comment by carlossg** [comment]
probably the same as #221
