### ISSUE TITLE
graal based image

### ISSUE THREAD

**Issue by joedomv** [carlossg/docker-maven#242]
Just putting it out there, is there any plans to support graal based image?

**Comment by carlossg** [comment]
I won't provide it, but PRs are welcome !

**Comment by rmie** [comment]
@joed14 I'm wondering if you have evidence/hints that this is actually worth the effort.

From what I understand, GraalVM biggest performance gain comes from ahead-of-time (AOT) compiling, but maven heavily depends on plugins that are loaded during runtime, which could render the expected performance gains marginal.
