### ISSUE TITLE
image won't resolve custom repository hostname

### ISSUE THREAD

**Issue by ericneu** [carlossg/docker-maven#243]
I'm new to Docker trying to learn so forgive me if this seems a stupid question.

I pulled down csanchez/maven:amazoncorretto-11, 
copied settings.xml to /root/.m2 to have our internal nexus repository and credentials
copied the project pom and source
but when I run mvn dependency it hangs then says it can't download the parent pom from our repository.
I've tried using the image to do a curl command to the parent pom and get an error resolving the hostname.
tried to use nslookup to verify DNS, but nslookup is not recognized in the image.

Any help would be greatly appreciated!

**Comment by carlossg** [comment]
this must be a misconfiguration of the Docker host DNS servers

**Comment by tlunsfordCXP** [comment]
For others who run into this, an option that solved it for me is to pass the --dns parameter in the docker run command to tell the container which IP address to use for DNS.
