### ISSUE TITLE
[DISCUSSION] Support for JDKs other than OpenJDK.

### ISSUE THREAD

**Issue by chtompki** [carlossg/docker-maven#25]
I'm completely open to the answer here being no, but I simply wanted to ask the question if there might be appetite for official maven docker images built on top of more than just the open JDK. Maybe the Oracle JDK and the IBM JDK. We in Apache Commons regularly test our distributions on those and were thinking about including them in our Travis-CI builds.

Thoughts?

**Comment by carlossg** [comment]
Are there Docker images for them?

**Comment by chtompki** [comment]
I know there's this:

* IbmJava: https://hub.docker.com/_/ibmjava/

But I don't know about OracleJava. I'll dig around to see if I can find what Travis-CI uses for that.

Also if you think it reasonable to include this in the supported maven images, then I'm happy to do the work and submit a PR.

**Comment by chtompki** [comment]
It seems that the use of the oracle-jdk has been sidelined due to licensing concerns. Would you want support for ibmjava in maven? I can work on that for you.
