### ISSUE TITLE
/root permission denied - maven:3.6-jdk-11

### ISSUE THREAD

**Issue by SabirAliShaik** [carlossg/docker-maven#257]
I am using maven:3.6-jdk-11 as base image. I am seeing /root: permission denied error in the container logs. Am i getting this error due to some permissions set by my organization or any issue in the base image. Could you please confirm on this.
![image](https://user-images.githubusercontent.com/63906251/150642008-0a91a652-cff6-4280-962a-a2379f0ce24b.png)

**Comment by carlossg** [comment]
not sure what's the question/issue?

see how to run as non root
https://github.com/carlossg/docker-maven#running-as-non-root-not-supported-on-windows

**Comment by SabirAliShaik** [comment]
Thanks for replying. I am able to run maven image in one environment. But when i try to run the same in kubernetes, i am getting /root permission denied error. I just want to confirm, is it due environment restrictions i am seeing this error.

**Comment by carlossg** [comment]
yes, it is environment restrictions
