### ISSUE TITLE
Introduce amazoncorretto + alpine images

### ISSUE THREAD

**Issue by dr29bart** [carlossg/docker-maven#269]
please, include amazoncorretto + alpine based image into the project.
https://github.com/corretto/corretto-docker

1. [11-alpine](https://hub.docker.com/_/amazoncorretto)
2. [8-alpine](https://hub.docker.com/_/amazoncorretto)
3. [17-alpine](https://hub.docker.com/_/amazoncorretto)

**Comment by sansmoraxz** [comment]
+
