### ISSUE TITLE
Request: add eclipse-temurin-8-alpine support

### ISSUE THREAD

**Issue by yjqg6666** [carlossg/docker-maven#273]
Only eclipse-temurin-8 is provided.

JDK is availabe at: [docker pull eclipse-temurin:8-jdk-alpine](https://hub.docker.com/layers/eclipse-temurin/library/eclipse-temurin/8-jdk-alpine/images/sha256-23e9b9dc441ac7574e7e3c851c1b2704cc776b2cdde145bd7f454e4a6d07b219?context=explore)

The PR #274 is done. PTAL.

**Comment by maffe** [comment]
I think this issue can be closed, #274 was merged and 3.9.3-eclipse-temurin-8-alpine, 3.9-eclipse-temurin-8-alpine, 3-eclipse-temurin-8-alpine image variants are available.
