### ISSUE TITLE
docker run command for Windows

### ISSUE THREAD

**Issue by Depechie** [carlossg/docker-maven#277]
Somehow I'm unable to start the docker image as a windows container.
Always get: `docker: invalid reference format: repository name must be lowercase`

The given documentation for the command is:
`docker run -it --rm --name my-maven-project -v "$(Get-Location)":C:/Src -w C:/Src csanchez/maven:3.3-jdk-8-windows mvn verify`

My tryout is:
`docker run -it --rm --name testmaven -p 8123:8080 -v "$(Get-Location)":C:/Projects/TestMaven -w C:/Projects/TestMaven  csanchez/maven:3.3-jdk-8-windows mvn verify`

Any guidance to get the windows based images going?

**Comment by slide** [comment]
You may want to try quoting the drive path for the volume:

`docker run -it --rm --name testmaven -p 8123:8080 -v "$(Get-Location)":"C:/Projects/TestMaven" -w C:/Projects/TestMaven  csanchez/maven:3.3-jdk-8-windows mvn verify`

I haven't had a chance to try it, but it might be what you are looking for

**Comment by slide** [comment]
Sorry, the quotes should go around the whole -v parameter value like this: 

```
docker run -it --rm --name testmaven -p 8123:8080 -v "$(Get-Location):C:/Projects/TestMaven" -w C:/Projects/TestMaven  csanchez/maven:3.3-jdk-8-windows mvn verify
```
