### ISSUE TITLE
Absence of JDK19-based builds

### ISSUE THREAD

**Issue by Euklios** [carlossg/docker-maven#305]
OpenJDK has pushed their 19th image approximately 2 months ago, but they somehow did not add it to the readme.

 * openjdk:19-oracle
 * openjdk:19
 * ...

So, here's the obvious question - where are Maven's docker images based on JDK19?

**Comment by carlossg** [comment]
see https://github.com/infosiftr/docker-library-docs/blob/master/openjdk/deprecated.md
