### ISSUE TITLE
Missing OpenJDK 19 images

### ISSUE THREAD

**Issue by denismakogon** [carlossg/docker-maven#306]
JDK 19 was released nearly 2 months ago, but still, there are no Maven images based on OpenJDK. The following images are missing:
- `3-openjdk-19`
- `3.8-openjdk-19`
- `3.8.6-openjdk-19`
- `*-openjdk-19-slim`

These images must be built on [this image](https://container-registry.oracle.com/ords/f?p=113:4:13977556581270:::4:P4_REPOSITORY,AI_REPOSITORY,AI_REPOSITORY_NAME,P4_REPOSITORY_NAME,P4_EULA_ID,P4_BUSINESS_AREA_ID:747,747,Oracle%20OpenJDK,Oracle%20OpenJDK,1,0&cs=3HmcN-xCFHP0QseG6LkNskgPDiBeRJisK4Qnz0li2RM3IJqx9ewdHjDY2PIBplBQl8ouN7yq9pDmJgvu5JUd2Sg):
```
container-registry.oracle.com/java/openjdk:<version>
```

**Comment by denismakogon** [comment]
Thank you for pointing to that issue, however, there is a public registry that offers OpenJDK images. So, what stops you from reintroducing Maven builds on top of those officially supported/maintained images? I didn't find any comments that **only** dockerhub images are allowed.

**Comment by carlossg** [comment]
what public registry?  In https://github.com/docker-library/openjdk/issues/505 it is said that openjdk docker images builds will not receive updates
docker-maven official docker images only can come from other official docker images
