### ISSUE TITLE
JAVA HOME PATH not defined correctly error thrown for ..sh file

### ISSUE THREAD

**Issue by ZuciGayathri** [carlossg/docker-maven#323]
Using markhobson/maven-chrome-jdk-8  for my selnium test 
(/usr/local/openjdk-8/)this is java  path whoch was working till 18 JAN 2023
recently faced belwo issue
 Command :   RUN mv /app/java.security /usr/local/openjdk-8/jre/lib/security/java.security thrown no such file or directly 
  modified  JAVA_HOME=/opt/java/openjdk and worked fine but later 

But all .sh files  executing maven command is throwing error as 
JAVA HOME PATH not defined correctly .

**Comment by carlossg** [comment]
openjdk-8 is deprecated and hasn't been updated in a while
