### ISSUE TITLE
No <dockerHost> given, no DOCKER_HOST environment variable, no read/writable '/var/run/docker.sock'

### ISSUE THREAD

**Issue by javierscope** [carlossg/docker-maven#334]
I'm using gitlab-ci.yml to build a docker image:

default:
  image: maven:3.8-openjdk-11

I'm able to execute **mvn clean package**, but when job executes **mvn deploy** or **mvn docker:build** I get next error:

[ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.39.1:build (default) on project simurai-orchestrator: Execution default of goal io.fabric8:docker-maven-plugin:0.39.1:build failed: No <dockerHost> given, no DOCKER_HOST environment variable, no read/writable '/var/run/docker.sock' or '//./pipe/docker_engine' and no external provider like Docker machine configured -> [Help 1]

What I'm missing?

**Comment by carlossg** [comment]
configuration is needed to build docker images from within a docker image, there are many tutorials out there
