### ISSUE TITLE
Add Maven docker image for windows based on the OpenJDK for windows images

### ISSUE THREAD

**Issue by iemejia** [carlossg/docker-maven#34]
I think it is a good idea to add the windows based maven images by extending the recently released openjdk docker images for windows:

https://github.com/docker-library/openjdk/blob/bd3c2a9867c9dc6a9a8425a8df5c54edf0cbf2cc/6-jdk/Dockerfile
https://github.com/docker-library/openjdk/blob/9745c87a15896ec558429a826e23926e721e4846/8-jdk/windows/windowsservercore/Dockerfile

**Comment by carlossg** [comment]
PRs welcome

**Comment by sarnobat** [comment]
I'd really like this too.

**Comment by carlossg** [comment]
closing because I don't have windows to try it, PRs welcome
