### ISSUE TITLE
Add "Packaging a local repository with the image" paragraph to dockerhub [Feature Request]

### ISSUE THREAD

**Issue by AverageS** [carlossg/docker-maven#35]
There is no comments about /root/.m2 folder being a volume right now in dockerhub page. It can be extremely frustrating to debug.

**Comment by ibnesayeed** [comment]
I feel like it should not be made a volume in the first place. If needed, users can make it a volume at run time or in their derived Dockerfile. I would strongly recommend to remove `VOLUME "$USER_HOME_DIR/.m2"` lines from each Dockerfile in this repo, unless there is a good reason to keep them that way.
