### ISSUE TITLE
Support building RPMs (for CentOS)

### ISSUE THREAD

**Issue by markhu** [carlossg/docker-maven#38]
To support the below `pom.xml` dependency, I submitted PR https://github.com/carlossg/docker-maven/pull/37

                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>rpm-maven-plugin</artifactId>

**Comment by carlossg** [comment]
This is a base image that you can extend, so it has the bare minimum packages needed

**Comment by markhu** [comment]
Ok, I added a short section to the README.md in PR #39 describing how to build local image.
