### ISSUE TITLE
Wrong docer example for eclipse-temurin-17 version?

### ISSUE THREAD

**Issue by Andre601** [carlossg/docker-maven#398]
Looking at the [Docker file for temurin 17](https://github.com/carlossg/docker-maven/blob/d7319e0caa2961b402073e8054bc63e8dc48d969/eclipse-temurin-17/Dockerfile) the example mentions `maven:3.9.4-eclipse-temurin-11` which cannot be right given it's an example for 17 and not 11.

Or is that intentional?

**Comment by carlossg** [comment]
all the dockerfiles use the maven package downloaded in the "master" eclipse-temurin-11 dockerfile but use the JDK correctly
