### ISSUE TITLE
How can I replace the settings.xml file?

### ISSUE THREAD

**Issue by medined** [carlossg/docker-maven#4]
Thanks for providing these container definitions. I have an Artifactory server that I'd like to use. Can I add a settings.xml to the container?

**Comment by carlossg** [comment]
You would extend the image and add any customizations that you would require as with any Docker image

**Comment by medined** [comment]
After a little thinking about my question, I added the settings.xml alongside the pom.xml then used this command to put the settings.xml in the correct directory inside the container. I think it's inelegant but it worked. Thanks!

docker run \
  -it \
  --rm \
  --link artifactory:artifactory \
  --name my-maven-project \
  -v "$PWD":/root/.m2 \
  -v "$PWD":/usr/src/mymaven \
  -w /usr/src/mymaven \
  maven:3.3-jdk-8 \
  mvn package

**Comment by xenoterracide** [comment]
I was also looking for some customization around this, though maybe I should file a bug regarding maven, would be nice to specify server settings right in the pom.xml, or maybe have that file searched for next to pom.xml
