### ISSUE TITLE
Git not available in the image

### ISSUE THREAD

**Issue by altus34** [carlossg/docker-maven#41]
Hi,
Why don't include some SCM (like Git) in the VM to be able to perform a release process ?

Thanks

**Comment by iemejia** [comment]
Git is available in the debian based image, so I asume you are using the alpine one, maybe you can add a PR to add this and see if the maintainer thinks is oke to add it, no ?

**Comment by carlossg** [comment]
this is a base image so it has only the basic packages, you can extend it
