### ISSUE TITLE
Corretto 21 + AL2023

### ISSUE THREAD

**Issue by a1flecke** [carlossg/docker-maven#412]
Thank you for creating a corretto-21 maven image.  I notice there is not a corretto21 + AL2023 image.  Do you plan on creating one?  Do you need any assistance with one?  My team needs one for our pipeline to better match what will be running in production, especially since the older AL linux images have an outdated libc

**Comment by carlossg** [comment]
You can submit a PR copying from the JDK 20 one, I won't be able to prepare it in the next weeks

**Comment by a1flecke** [comment]
@carlossg Thanks for the quick reply.  Here is my PR: https://github.com/carlossg/docker-maven/pull/413

**Comment by a1flecke** [comment]
@carlossg thanks for merging the pr. Is anything else needed to release the image?

**Comment by carlossg** [comment]
My images should be automatically built. 

For the dockerhub official image you would need to run ./publish.sh and submit a PR to https://github.com/docker-library/official-images

**Comment by a1flecke** [comment]
@carlossg  thanks for the instructions.  I was able to create the PR: https://github.com/docker-library/official-images/pull/15442

Please let me know if something else is needed.
