### ISSUE TITLE
maven: 3.6.3-openjdk-21

### ISSUE THREAD

**Issue by channingli8** [carlossg/docker-maven#427]
I notice there is no image like `maven: 3.6.3-openjdk-21` for open JDK. Do you plan on creating one? I see we have images like `maven: 3.6.3-openjdk-17`,  `maven: 3.6.3-openjdk-15`.

**Comment by carlossg** [comment]
openjdk upstream images are deprecated and not built anymore, see https://github.com/docker-library/openjdk?tab=readme-ov-file#deprecated
