### ISSUE TITLE
Include the specific jdk version as part of the image (and its tags)

### ISSUE THREAD

**Issue by iemejia** [carlossg/docker-maven#43]
It would be really nice to be able to address the specific version of the JDK available with the maven docker image, e.g. maven:3.5.0-8u141

Fixing a specific openjdk version in the docker image gives the advantage of having reproducible builds based on the maven docker image, because with this we can guarantee that code compiled with a specific combination of maven and openjdk version will produce the exact same results which is not the case if we let the tag open as it is today, e.g. a user can download the docker image in different moments and get different versions of the openjdk so he won't be able to reproduce the builds because different versions of the compiler can generate different bytecode.

Of course the bad part is that this implies a little bit of extra maintenance because we will need to update the version of the JDK when a new version is released, however this is really not frequent and in any case most of the users wouldn’t even notice that they are not using the latest in case that this takes some time :) but in revenge we win a really valuable use case for this docker image.

**Comment by iemejia** [comment]
Hello again, one more reason to do this, we are starting work on reproducible builds on maven upstream!
https://issues.apache.org/jira/browse/MNG-6276
Please please !

**Comment by carlossg** [comment]
you can still do this using SHA. The official images are rebuilt from time to time and tags rewritten even if they are set in this repo

**Comment by iemejia** [comment]
Thanks @carlossg yes we can do this with the SHA, but having the explicit version so users of the image can pin it to be the best practice. I know that this adds a bit of extra work for the maintenance of this image, but the gains are worth the extra work in my opinion.

**Comment by carlossg** [comment]
it doesn't matter what it is done here, the Docker official library team will rebuild these images and the parent images. I have seen it before and unless SHAs are used there are no guarantees that tags will not be changed

**Comment by carlossg** [comment]
moving discussion to #56
