### ISSUE TITLE
Image for maven 3.9.6 + azuluzulu-8

### ISSUE THREAD

**Issue by phaniteja-nunna** [carlossg/docker-maven#441]
Currently there is no image available for maven 3.9.6 + azulzulu-8. Are there any plans to make this image available? Thank you. @carlossg

**Comment by phaniteja-nunna** [comment]
I am open to contribute to buld this image.

**Comment by phaniteja-nunna** [comment]
@carlossg I have added the Docker files in my fork here: https://github.com/phaniteja-nunna/docker-maven

When I run the github-action-generation script, I get the below error. Any idea how it can be resolved?
% sh github-action-generation.sh
common.sh: line 12: jdk: unbound variable

**Comment by phaniteja-nunna** [comment]
@carlossg I have created a PR. Please review.

**Comment by carlossg** [comment]
https://github.com/carlossg/docker-maven/pull/442
