### ISSUE TITLE
Issue with 3.5.0-jdk-8-alphine

### ISSUE THREAD

**Issue by SunithaR** [carlossg/docker-maven#46]
When using maven:3.5.0-jdk-8-alphine
and running mvn install, I get the below error.
java.lang.UnsatisfiedLinkError: /usr/lib/jvm/java-1.8-openjdk/jre/lib/amd64/libfontmanager.so

On researching this error is a result of using FROM openjdk:8-jre-alpine which has the issue. Alphine has not fixed this issue yet. The work around suggested is to use FROM openjdk:8u121-jre-alpine. 
Can the maven container be updated to use this version of openjdk alphine until the issue is fixed? or better yet, can a minor version be specified which can then be used to get the specific jdk version when building the maven image?

**Comment by carlossg** [comment]
Can you submit a PR ?

**Comment by SunithaR** [comment]
Thank you for updating this quickly!
