### ISSUE TITLE
Support for arm64, temurin 17 and alpine?

### ISSUE THREAD

**Issue by victornoel** [carlossg/docker-maven#465]
Hi,

I noticed that for arm64, there is support for
- temurin 17 and ubuntu
- temurin 21 and alpine

But no support for temurin 17 and alpine.

Is there any way to add it?

Thanks!

**Comment by carlossg** [comment]
there is no upstream temurin 17 alpine arm64

https://github.com/docker-library/official-images/blob/3db9ea7/library/eclipse-temurin#L246-L249

**Comment by victornoel** [comment]
@carlossg ha, that is why, this makes sense then… I will try to see if I can ask for it :)

**Comment by victornoel** [comment]
FYI I created https://github.com/adoptium/containers/issues/566, I will come back here if it is ever solved :)

**Comment by victornoel** [comment]
In the end, apparently the combination of Java 17, ARM64 and Alpine is unfortunately not considered stable (cf https://github.com/adoptium/containers/issues/566#issuecomment-2146277160).

Cheers
