### ISSUE TITLE
Not authorized, ReasonPhrase:Unauthorized - custom settings.xml

### ISSUE THREAD

**Issue by prasenjithaty** [carlossg/docker-maven#48]
Hi,

I've configured the server section of a custom settings.xml file to include the username/password and have copied it to create a custom image. Here is the content of my Dockerfile

```
FROM maven:3.5.0-jdk-8-alpine
COPY settings.xml /usr/share/maven/ref/
```

With the same credentials in the settings.xml I'm able to login to nexus as well as resolve dependencies (if I directly run `mvn dependency:resolve` on my MacBook), but it is throwing 401 while running from docker. Below is the error:

```
[ERROR] Failed to execute goal on project my-app: Could not resolve dependencies for project com.home.myapp:my-app:jar:0.0.1-SNAPSHOT: Failed to collect dependencies at com.home.pages:content-core:jar:0.0.28: Failed to read artifact descriptor for com.home.pages:content-core:jar:0.0.28: Could not transfer artifact com.home.pages:content-core:jar:0.0.28 from/to release-repo (http://my-private-repo.com/repositories/releases/): Not authorized , ReasonPhrase:Unauthorized. -> [Help 1]
```

Please help.

**Comment by AyushyaChitransh** [comment]
I think you need to copy `security-settings.xml` too. 

Quoting https://stackoverflow.com/a/39540485/6207775

> In my case, my problem was I had copied over my maven ~/.m2/settings.xml file, which itself specifies "username and passwords" without realizing that if you do that, if there is also a file security-settings.xml, you need to copy that over too (it double hashes): https://developer.jboss.org/wiki/Mavensettingsxmlmaskingpassword?_sscc=t
> 
> My hunch/assumption is that if the security-settings.xml file is absent, maven happily uses the passwords from settings.xml 'without double hashing' them so they are presented wrong to the server.

**Comment by Scrayos** [comment]
You seem to be copying to the wrong location. I use `COPY maven/settings.xml /root/.m2/settings.xml` which works perfectly fine.

**Comment by prasenjithaty** [comment]
Figured it out myself. Documentation is a little misleading. Sorry for not closing the issue earlier.
