### ISSUE TITLE
docs(README): should User Feedback continue to reference Freenode

### ISSUE THREAD

**Issue by timothystone** [carlossg/docker-maven#485]
Generic question, could have a PR quickly, but should the [README continue to reference Freenode](https://github.com/carlossg/docker-maven?tab=readme-ov-file#issues)? 

> You can also reach many of the official image maintainers via the `#docker-library` IRC channel on Freenode.

Is this Libera.Chat now?

**Comment by timothystone-knsl** [comment]
> You can also reach many of the official image maintainers via the `#docker-library` IRC channel on [Libera.Chat (web)](https://web.libera.chat/#docker-library) or in your favorite IRC client.

**Comment by carlossg** [comment]
yes https://github.com/docker-library/official-images?tab=readme-ov-file#contributing-to-the-standard-library
