### ISSUE TITLE
Azul Debian variants

### ISSUE THREAD

**Issue by anirbanmu** [carlossg/docker-maven#489]
👋I see that Azul has an image for Debian [here](https://hub.docker.com/r/azul/zulu-openjdk-debian), would you be open to a PR adding a new Debian variant for Azul here in addition to the already present Linux images for Azul (Ubuntu & Alpine)? I think the Dockerfile for this Debian variant is going to be very simple since there's already an upstream Debian image.

Additional side question too - are the Azul Maven images not allowed to be official images under https://hub.docker.com/_/maven? EDIT: I think I may have deduced the answer here. The upstream Azul container images aren't official to begin with, huh? That's probably the reason the Maven Azul images can't be official images?

**Comment by carlossg** [comment]
we can add it, and you are correct about official images

**Comment by anirbanmu** [comment]
sounds good, I'll work on PR for it 👍
