### ISSUE TITLE
Update to Maven 3.5.2 

### ISSUE THREAD

**Issue by iemejia** [carlossg/docker-maven#51]
Maven 3.5.2 was released some days ago so maybe a good idea to update the version.

**Comment by shark-horse** [comment]
Moreover, the jdk-8 Maven 3.5.0 Docker image will not build anymore as the Maven binary has been removed:

`Step 6/13 : RUN mkdir -p /usr/share/maven /usr/share/maven/ref   && curl -fsSL -o /tmp/apache-maven.tar.gz ${BASE_URL}/apache-maven-${MAVEN_VERSION}-bin.tar.gz   && echo "${SHA}  /tmp/apache-maven.tar.gz" | sha256sum -c -   && tar -xzf /tmp/apache-maven.tar.gz -C /usr/share/maven --strip-components=1   && rm -f /tmp/apache-maven.tar.gz   && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn
 ---> Running in 26773af9507e
curl: (22) The requested URL returned error: 404 Not Found`
