### ISSUE TITLE
Corretto GPG key expired

### ISSUE THREAD

**Issue by zanonjonas** [carlossg/docker-maven#519]
Hello,

I use maven:3-amazoncorretto-21-debian as base image. When apt-get update is ran on my Dockerfile, I get the error:

`13.20   The following signatures were invalid: EXPKEYSIG A122542AB04F24E3 Amazon Services LLC (Amazon Corretto release) <corretto-team@amazon.com>`

The key was already renewed on: https://github.com/corretto/corretto-21/issues/82

I think you might need to rebuild amazoncorretto images or I'm having some caching issues on my side.

Thanks.

**Comment by Lyrkas** [comment]
Hi, seems like were having the same problem. Hoping to get a fix soon!

**Comment by alexist** [comment]
same issue

**Comment by gauthier-fox** [comment]
Hello, we have the same problem with `maven:3-amazoncorretto-11-debian`.

**Comment by Rudometov** [comment]
The images need to be rebuilt. We are reaching out to dockerhub asking to rebuilt these. 
Couple workarounds: 

Rebuilding the image from dockerfile works. 

If the image has the old key, one of the workarounds would be to explicitly download the new key. oneliner script example:
`apt update ; apt install -y gpg wget &&  rm /usr/share/keyrings/corretto.gpg && wget -O - https://apt.corretto.aws/corretto.key | gpg --dearmor -o /usr/share/keyrings/corretto.gpg && apt update`

**Comment by carlossg** [comment]
fixed by https://github.com/docker-library/official-images/issues/18021

you could use [csanchez/maven](https://hub.docker.com/r/csanchez/maven)
[maven](https://hub.docker.com/_/maven) and [ghcr.io/carlossg/maven](https://github.com/carlossg/docker-maven/pkgs/container/maven) in the meantime

**Comment by cjoyau** [comment]
I opened a PR with the changes suggested [here](https://github.com/docker-library/official-images/issues/18021#issuecomment-2524684806). It should trigger a rebuild of the docker maven:*amazoncorretto-*-debian images by docker-library.

**Comment by cjoyau** [comment]
I opened a PR with the changes suggested [here](https://github.com/docker-library/official-images/issues/18021#issuecomment-2524684806).
It should trigger a rebuild of the `maven:*amazoncorretto-*-debian` images by docker-library.
