### ISSUE TITLE
Issues pulling images after last update (3.5.2)

### ISSUE THREAD

**Issue by whitfin** [carlossg/docker-maven#52]
After the latest update, there are issues pulling the images. I thought it might be a cache thing but it looks like it's not getting fixed (been a couple of hours I've been trying).

```bash
$ docker pull maven:3.5-jdk-8-alpine
3.5-jdk-8-alpine: Pulling from library/maven
no matching manifest for linux/amd64 in the manifest list entries
```

Is there something that needs to be configured manually? It looks like this image just migrated to the Docker Store so I was wondering if that's related somehow. Note that I can pull images before the update today (e.g. 3.5.0 still works).

**Comment by carlossg** [comment]
This should be raised in https://github.com/docker-library/official-images/pull/3649

**Comment by carlossg** [comment]
fixed already
