### ISSUE TITLE
3.5-jdk-8-alpine: no longer able to build java code

### ISSUE THREAD

**Issue by RayPlante** [carlossg/docker-maven#53]
I use maven:3.5-jdk-8-alpine as the base container for a container that builds java code using maven.  The maven build now fails with the error: 
```
No compiler is provided in this environment.  Perhaps you are running on a JRE rather than a JDK?
```
Looking at the 3.5-jdk-8-alpine Dockerfile, I see this message appears to be true as the maven Dockerfile now says:
```
FROM openjdk:8u121-jre-alpine
```
This was changed  from using "jdk" instead of "jre" with commit b7f10a80f31, as illustrated here: https://github.com/carlossg/docker-maven/commit/b7f10a80f31e03d30200ffd98bea61e3e3a8f517#diff-fbac60dc291168cfb53991ab429c34fc.  This was to address issue #46.

I'm assuming the main motivation for the maven images is to build Java code, so a jdk version is needed.  It appears that the simple fix would be to use openjdk:8u121-jdk-alpine

**Comment by demaniak** [comment]
Just hit this exact same problem, using `maven:3-jdk-8-alpine`

**Comment by lupo112** [comment]
Same here: `maven:3.5-jdk-8-alpine`

**Comment by lupo112** [comment]
See line: https://github.com/carlossg/docker-maven/blob/93d297ed2fc952af8c3638eae78c3d5e7526033f/jdk-8-alpine/Dockerfile#L2

**Comment by demaniak** [comment]
Yup. #54  will fix it...somebody just needs to accept the PR....
