### ISSUE TITLE
Dependency Projects

### ISSUE THREAD

**Issue by vijaysankarmanchi** [carlossg/docker-maven#58]
I have 2 repositories in bitbucket. Now when pipeline is configured for both the repositories i am able to build repo 1 successfully and repo 1 is the dependency project of repo 2 . When i am trying to build repo 2 it says Could not resolve dependencies for project repo 1 project.
Please find the below yml i have configured.
image: maven:3.3.9

pipelines:
  default:
    - step:
        caches:
          - maven
        script: # Modify the commands below to build your repository.
          - mvn -s settings.xml # e.g. with settings.xml in the root of the project  
          - mvn clean install package # -B batch mode makes Maven less verbose

Any suggestions how to resolve repo 1 dependency in repo 2

**Comment by carlossg** [comment]
question should be asked in maven-users mailing list, this is just for issues with the docker image
