### ISSUE TITLE
Mavan:3.5-JDK-8 uses incorrect version of Maven

### ISSUE THREAD

**Issue by LorneCurrie** [carlossg/docker-maven#60]
When you down load docker image `maven:3.5-jdk-8` and run the following commend, the maven version is not `3.5.0`, but `3.5.2`.  Using the above docker container, I would expect version `3.5.0`.

![screen shot 2017-12-15 at 10 25 32 am](https://user-images.githubusercontent.com/16747823/34015159-7fc162e6-e182-11e7-9a05-0814bad3e906.png)

**Comment by carlossg** [comment]
3.5 is the latest 3.5.x
