### ISSUE TITLE
Can't find my .jar file after running mvn clean install in my image

### ISSUE THREAD

**Issue by nagarjun** [carlossg/docker-maven#61]
Hello. I am new to JAVA and Docker so please spare me. I also asked for help on [StackOverflow](https://stackoverflow.com/questions/48075454/docker-image-cannot-read-find-a-jar-file-from-another-image) but did not get any help. Essentially, I have two Java projects:

- project-cms
- project-app

I am using maven:3.5.2-jdk-8-alpine to build an image from project-cms and then trying to build an image of project-app using the image created from project-cms. project-app has a dependency on a .jar file that project-cms generates when I run `mvn clean install`. However, my Docker image for project-app does not build because it cannot find the .jar file within the image created from project-cms. This is how my two Docker files look:

**project-cms/Dockerfile**

```
FROM maven:3.5.2-jdk-8-alpine
LABEL Name=project-cms Version=1.0.0 

# Container configuration
RUN mkdir /project-cms
COPY . /project-cms
WORKDIR /project-cms
VOLUME /project-cms
RUN mvn clean install
```

**project-app/Dockerfile**

```
FROM project-cms:latest
LABEL Name=project-app Version=1.0.0 

# Container configuration
RUN mkdir /app
COPY . /app
WORKDIR /app
VOLUME /app
RUN mvn clean install && mvn build
EXPOSE 8080
CMD [ "mvn", "tomcat7:run" ]
```

When I run `docker image ls` after building the project-cms/Dockerfile, everything looks good and so I try to build project-app/Dockerfile. This is where it breaks in the RUN step. My understanding is that the required .jar file is not available in the project-cms image's .m2 folder. To check this, I ran `docker run -it project-cms sh` and looked into the .m2 folder and all I could find were two files:

- copy_reference_file.log
- settings-docker.xml

I am not sure where any of the dozens of dependencies listed in my .pom file are. Can someone please help me resolve this?

**Comment by carlossg** [comment]
the maven local repo is a volume in previous versions of the image, see #57

it should work if you use `FROM maven:3.5-jdk-8-alpine`
