### ISSUE TITLE
Docker maven images alpine velocity issue

### ISSUE THREAD

**Issue by Tony-Proum** [carlossg/docker-maven#69]
Alpine version of docker maven (3.5.2-jdk-8-alpine) does'nt allow to use openclover to run a code analysis.
Running maven clean install using clover maven plugin results in a NullPointerException trying to reach a velocity template (.vm file)

This issue is not reproducible using the regular version of maven image (3.5.2-jdk-8) 

## Test Case
you can reproduce this issue using a little project with this plugin 

```			
<plugin>
    <groupId>org.openclover</groupId>
    <artifactId>clover-maven-plugin</artifactId>
    <version>4.2.1</version>
    <configuration>
         <generateJson>true</generateJson>
    </configuration>
    <executions>
        <execution>
            <id>clover</id>
            <phase>verify</phase>
            <goals>
                <goal>setup</goal>
                <goal>check</goal>
                <goal>aggregate</goal>
                <goal>clover</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

**Comment by carlossg** [comment]
maybe openclover can't just run in alpine ?

**Comment by Tony-Proum** [comment]
I guess provided it's just a jar that's allowed to run on another versions of this image, it seems like there is a missing lib in alpine one.
Indeed maybe you're right, but I can't figure out why this jar is not able to run specifically on this java environment.
Have you an idea ?
