### ISSUE TITLE
Using private repositories

### ISSUE THREAD

**Issue by winniwinter** [carlossg/docker-maven#7]
Hi I want to just build my java project with this image. The problem is, that I have a private repository to download artifacts from. Is it somehow possible to configure the image to add private repositories?

**Comment by carlossg** [comment]
just mount your settings.xml in /root/.m2/ or whatever HOME you use

**Comment by winniwinter** [comment]
ok, 
I see. My main idea of using the maven docker image so people without maven could build the artifact (frontend devs). The created artifact is used later on to start another container with the artifact. Therefore the users do not have maven installed. 

But I could basically provide the settings.xml within the project or create a new image with the settings.xml baked in.

**Comment by richardskg** [comment]
Why was /root/.m2 made into a volume? I was trying to place a repository in there and it wasn't saving in the new image. From the Dockerfile reference on VOLUME: 
Note: If any build steps change the data within the volume after it has been declared, those changes will be discarded.

I can put the repository some different place, but that is something I will probably forget about in a few months.

**Comment by nvdk** [comment]
I second @richardskg's request to remove to volume specification from the dockerfile. I created a separate issue for it (#11)

**Comment by carlossg** [comment]
The readme has been updated to show how to add settings.xml to an image
