### ISSUE TITLE
Image maven:3.5-jdk-8 throws error Could not find ssh-agent: IOException: Cannot run program "ssh-agent"

### ISSUE THREAD

**Issue by midalias** [carlossg/docker-maven#74]
We have several jobs in CloudBees Jenkins Enterprise that were using image maven:3.5-jdk-8 to run scripts. Some of the commands in those scripts are ssh and scp. Yesterday those jobs were running correctly. Today they throw error: 

"Could not find ssh-agent: IOException: Cannot run program "ssh-agent": error=2, No such file or directory
Check if ssh-agent is installed and in PATH
scp: command not found
ssh: command not found"

While troubleshooting, I created a container and executed "ls -l /usr/bin/ssh" and got:
"ls: cannot access '/usr/bin/ssh': No such file or directory"

To resolve the issue we are now using a different image. I just wanted to let you know about this problem and know if this was an intended change in the Docker image.

Regards.

Idalia Solis-Loeser
DevOps Engineer

**Comment by voy13k** [comment]
git and other scm's are now missing as well.

**Comment by raehalme** [comment]
There was a hickup in the openjdk project due to mistake in tagging images. As a result tools such as git (and maybe others as well) were accidentally removed from the openjdk image. See [this issue](https://github.com/docker-library/openjdk/issues/180) for more details.

**Comment by tianon** [comment]
As noted, this should be resolved now (for a few days now). :+1: :heart:

**Comment by carlossg** [comment]
Thanks @tianon

**Comment by micwin** [comment]
Is this problem open again? I faced maven:3-jdk-8-alpine not having ssh installed...
