### ISSUE TITLE
git executable not part of image anymore?

### ISSUE THREAD

**Issue by GitMarco** [carlossg/docker-maven#75]
Since 29 march 2018 a new version of _maven:3-jdk-8_ was released, I'm getting this error when running mvn clean install within that image:

> [ERROR] Failed to execute goal org.codehaus.mojo:buildnumber-maven-plugin:1.4:create (useLastCommittedRevision) on project abc: Cannot get the revision information from the scm repository : 
> [ERROR] Exception while executing SCM command.: Error while executing command. Error while executing process. Cannot run program "git" (in directory "/builds/xyz"): error=2, No such file or directory
> 

So during the maven buildnumber plugin.

The mvn command and plugin works fine again after installing git again via: _apt-get install git_

But then the build failed with:

> [ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?

To fix that I also had to upgrade the surefire and failsafe plugins to 2.21.0. 

Am I missing something that has changed related to git not being present anymore in the image?

**Comment by carlossg** [comment]
see #74
