### ISSUE TITLE
Latest `3.5-jdk-8` Docker image cause `failsafe` to fail

### ISSUE THREAD

**Issue by raghavan20** [carlossg/docker-maven#76]
```
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:44 min
[INFO] Finished at: 2018-04-09T11:38:52Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.19.1:integration-test (default) on project XYZ: Execution default of goal org.apache.maven.plugins:maven-failsafe-plugin:2.19.1:integration-test failed: java.lang.StringIndexOutOfBoundsException: String index out of range: -1 -> [Help 1]
```

Docker image: `maven:3.3-jdk-8 mvn failsafe:integration-test`

Even though there were no failures or errors from the tests, `failsafe` plugin seem to fail with exception `StringIndexOutOfBoundsException`. With `mvn -X` it was related to `jansi`. But when running in batch mode using `-B` it was throwing another exception `ConcurrentModificationException`. Also during some of the executions, the tests would be stuck / blocked at some point while running test suite and would not proceed to completion.

**Comment by carlossg** [comment]
you should raise it in Maven jira
http://maven.apache.org/surefire/maven-failsafe-plugin/jira-report.html

**Comment by raghavan20** [comment]
Okay thanks. I have raised one `https://issues.apache.org/jira/browse/SUREFIRE-1513`

**Comment by slachiewicz** [comment]
@raghavan20 in the issue you mention maven 3.5 but in the description docker image maven:3.3-jdk-8. 
Please retest locally with latest maven 3.5.4 and then again with the latest docker based Maven.
