### ISSUE TITLE
Can't set MAVEN_CONFIG with docker --env

### ISSUE THREAD

**Issue by neilhwatson** [carlossg/docker-maven#77]
```docker run -it --rm --user 1000 --name rest-builder -e HOME=/tmp -e MAVEN_CONFIG=/tmp/.m2 maven:3-jdk-8-alpine env```

Should show MAVEN_CONFIG set, but it doesn't:

```
LANG=C.UTF-8
HOSTNAME=75b2c4f4c9a8
MAVEN_HOME=/usr/share/maven
JAVA_HOME=/usr/lib/jvm/java-1.8-openjdk
JAVA_VERSION=8u151
PWD=/
HOME=/tmp
TERM=xterm
SHLVL=0
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/jvm/java-1.8-openjdk/jre/bin:/usr/lib/jvm/java-1.8-openjdk/bin
JAVA_ALPINE_VERSION=8.151.12-r0
BASH_FUNC_copy_reference_file%%=() {  local root="${1}";
 local f="${2%/}";
 local logfile="${3}";
 local rel="${f/${root}/}";
 echo "$f" >> "$logfile";
 echo " $f -> $rel" >> "$logfile";
 if [[ ! -e ${MAVEN_CONFIG}/${rel} || $f = *.override ]]; then
 echo "copy $rel to ${MAVEN_CONFIG}" >> "$logfile";
 mkdir -p "${MAVEN_CONFIG}/$(dirname "${rel}")";
 cp -r "${f}" "${MAVEN_CONFIG}/${rel}";
 fi
}
```

**Comment by carlossg** [comment]
MAVEN_CONFIG is used internally only then unset

**Comment by neilhwatson** [comment]
Sorry I don't understand your comment. On this page: https://hub.docker.com/_/maven/, section "Running as non-root" is shows an example of setting MAVEN_CONFIG.

**Comment by carlossg** [comment]
And that example works. The `MAVEN_CONFIG` env var is used and then is unset.
It is unset because other tools use the same name variable 0490eff01e529b2d94789511b008d01a7b314953
