### ISSUE TITLE
Maven ignores $HOME/.m2 directory

### ISSUE THREAD

**Issue by neilhwatson** [carlossg/docker-maven#78]
Using docker run command below I'd expect mvn commands to download plugins to /tmp/.m2/repository, instead it downloads them to './?/.m2/repository' in the current directory. 
```
#!/bin/bash -x

WORKDIR=/usr/src/mymaven
CHOME=/tmp

docker run -it --rm  --user ${UID} --name rest-builder \
   -e HOME=${CHOME} \
   -w ${WORKDIR} \
   -v ${PWD}:${WORKDIR} \
   -v ${HOME}/.m2:${CHOME}/.m2 \
   maven:3-jdk-8-alpine sh
```

**Comment by carlossg** [comment]
That is explained here https://github.com/carlossg/docker-maven#running-as-non-root and here https://blog.csanchez.org/2017/01/31/running-docker-containers-as-non-root/
