### ISSUE TITLE
Can't write in /var/maven when running as another user

### ISSUE THREAD

**Issue by Throckmortra** [carlossg/docker-maven#83]
The error:
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.163 s
[INFO] Finished at: 2018-05-16T23:17:02Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.4.0.905:sonar (default-cli) on project test-maven: Unable to create user cache: /var/maven/.sonar/cache -> [Help 1]
```

The docker run command printed by the Jenkins job (trimmed the workspace string):
```
docker run -t -d -u 1001:1001 -v /myworkspace/.jenkins/etc/passwd:/etc/passwd:ro -v /home/jenkins/.m2:/var/maven/.m2 -e MAVEN_CONFIG=/var/maven/.m2 -w /myworkspace -v /myworkspace:/myworkspace:rw,z -v /myworkspace@tmp:/myworkspace@tmp:rw,z -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** maven:3.5.3-jdk-10 cat
```

How it's being used in Jenkins:
```
def mvn(String goals) {
   docker.image("maven:3.5.3-jdk-10").inside("${args}") {
       sh "mvn -B -Duser.home=/var/maven ${goals}"
   }
}
```

**Comment by deogracia** [comment]
Hi,
with the provided example in the "Running as non-root" chapter, it may depend on the existence on ~/.m2 and its permissions

Here's my setup

* Docker version 17.12.0-ce, build 486a48d270
* OS: Linux Chakra (archlinux' spinoff)
* command used:
```
docker run -v ~/.m2:/var/maven/.m2 -ti --rm -u 1000 -e MAVEN_CONFIG=/var/maven/.m2 maven:3.3-jdk-8 mvn -Duser.home=/var/maven archetype:generate
```

Results:
* without an existing ~/.m2
```
touch: cannot touch ‘/var/maven/.m2/copy_reference_file.log’: Permission denied
Can not write to /var/maven/.m2/copy_reference_file.log. Wrong volume permissions?
```
A ~/.m2 directory is created but with the following permission:
```
ls -lha ~ |grep m2
drwxr-xr-x  2 root      root      4,0K 05.06.2018 14:04 .m2/
```
*  with an existing ~/.m2 (created from scratch and empty with mkdir -p ~/.m2)
```
ls -lhna ~ |grep m2
drwxr-xr-x  2 1000 1000 4,0K 05.06.2018 14:12 .m2/

```

Docker run's output
```
docker run -v ~/.m2:/var/maven/.m2 -ti --rm -u 1000 -e MAVEN_CONFIG=/var/maven/.m2 maven:3.3-jdk-8 mvn -Duser.home=/var/maven archetype:generate
[INFO] Scanning for projects...
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.5/maven-clean-plugin-2.5.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.5/maven-clean-plugin-2.5.pom (4 KB at 14.0 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/22/maven-plugins-22.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/22/maven-plugins-22.pom (13 KB at 530.6 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/21/maven-parent-21.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/21/maven-parent-21.pom (26 KB at 990.0 KB/sec)
[...]
```

listing of ~/.m2
```
ls -lhna ~/.m2
total 20K
drwxr-xr-x  3 1000 1000 4,0K 05.06.2018 14:14 ./
drwx------ 43 1000 1000 4,0K 05.06.2018 14:13 ../
drwxr-xr-x 14 1000    0 4,0K 05.06.2018 14:14 repository/
-rw-r--r--  1 1000    0  199 05.06.2018 14:14 copy_reference_file.log
-rw-r--r--  1 1000    0  327 05.06.2018 14:14 settings-docker.xml
```

try ``ls /home/jenkins/.m2```, it may give you some insights about what gone wrong.

**Comment by carlossg** [comment]
you can't just mount a random dir from the host with any permissions and expect it to work inside a container, see comments from @deogracia

**Comment by Throckmortra** [comment]
@carlossg that isn't a random directory from the host, it is the jenkins user .m2. The same Jenkins user that I am also mounting. Sorry If my original comment wasn't clear, the Jenkins user definitely has permission to write in its own .m2 directory, and it does so just fine when running maven commands outside of the docker container.
```
[jenkins@jenkins-build-slave-1 ~]$ ls -lha
drwxrwxr-x.  3 jenkins jenkins 4.0K May  8 16:55 .m2
```

```
[jenkins@jenkins-build-slave-1 .m2]$ ls -lha
total 36K
drwxrwxr-x.  3 jenkins jenkins 4.0K May  8 16:55 .
drwx------.  9 jenkins jenkins 4.0K May 11 02:09 ..
-rw-r--r--.  1 jenkins jenkins  13K May 21 14:04 copy_reference_file.log
drwxrwxr-x. 37 jenkins jenkins 4.0K May  9 18:13 repository
-rw-r--r--.  1 jenkins jenkins  327 May  8 16:55 settings-docker.xml
-rw-r--r--.  1 jenkins jenkins 2.5K May  7 21:16 settings.xml
```

**Comment by deogracia** [comment]
I didn't pay enough attention to your error message: the failure is on **/var/maven/.sonar/cache**.

I found this issue because I didn't see that I had a permission issue on **~/.m2**

In your case, check from a fresh container without anything mounted, the permission on **/var/maven**=> It should belongs to root:root, which explain why you can't as uid 1001 write on it.

If that's the case, you could
* either change **/var/maven** permission ( by building your own image based on this one),
* either, mount a directory owned by uid 1001 on /var/maven

I'm not sure if even one is a good solution. As for myself, I run mvn as root and after run a chown -R 1001. It's not what I wanted at first, but it works.

**Comment by OldFatCactus** [comment]
Sorry @deogracia , the first option is difficult for me. I don't want to maintain my own images, I want to trust that official Maven images can be used in a normal capacity. 

I don't know what you mean by the second option, the directory I mounted to /var/maven is owned by UID 1001.

Appreciate your suggestions though
