### ISSUE TITLE
/usr/local/bin/mvn-entrypoint.sh: line 39: exec: -u: invalid option

### ISSUE THREAD

**Issue by rgrsoucy** [carlossg/docker-maven#84]
When trying to use the **maven:latest** image with the **docker-plugin** for **Jenkins**, I am getting the following error when Jenkins tries to start the container:

Can not write to /root/.m2/copy_reference_file.log. Wrong volume permissions? Carrying on ...
**/usr/local/bin/mvn-entrypoint.sh: line 39: exec: -u: invalid option**

Not sure if the issue is with the **docker-plugin** or with the **mvn-entrypoint.sh** itself?

**Comment by carlossg** [comment]
it's the docker plugin passing some options to this image
