### ISSUE TITLE
Docker beginner : facing issue while running spring boot app

### ISSUE THREAD

**Issue by komalbhola** [carlossg/docker-maven#87]
Hi, 
I am trying to run a spring boot app(basic - just a controller displaying welcome !) on docker. 
Image is getting created successfully, but when I run it, it says below error. 

![errordocker](https://user-images.githubusercontent.com/4113015/45021453-3c936e00-b04f-11e8-9ea6-23d0a0214c60.PNG)

**Comment by panteparak** [comment]
Can you share your Dockerfile

I also experience this problem in the newer versions of this image

**Comment by carlossg** [comment]
what does your image have to do with this maven image ?
