### ISSUE TITLE
SVN Error (E235000) when running "mvn release:prepare"

### ISSUE THREAD

**Issue by veenified** [carlossg/docker-maven#9]
I get the following error when running `mvn release:prepare`...
```
[ERROR] svn: E235000: In file '/build/subversion-Hohtq2/subversion-1.8.10/subversion/libsvn_client/copy.c' line 1386: assertion failed (commit_items != NULL)
```
Could this be a error with the particular version of SVN included in the image?

**Comment by carlossg** [comment]
the svn included is the default debian package, probably added transitively in the parent java image

**Comment by veenified** [comment]
I am no longer getting this issue. Not sure what changed... if anything, but I am just glad to have it working.

**Comment by zbycz** [comment]
Google took me to this issue for this error.

I had to make the svn url from `"svn info"` the same as in `"pom.xml - scm.base"` using `svn switch --relocate` as suggested [here](https://rterp.wordpress.com/2012/02/11/issues-with-server-names-and-maven-subversion-scmtag-goal/)

**Comment by aditya-narain** [comment]
@zbycz , thanks for pointing out the link. I was pretty much struggling the whole time yesterday for figuring this out. We essentially need to make sure scm connection is pointing to the right location.
