### ISSUE TITLE
Latest pointing to jdk 8

### ISSUE THREAD

**Issue by waghanza** [carlossg/docker-maven#93]
Hi,

I can see that docker image, with the `tag` **latest** use `jdk` **8**.

However, there is the `jdk` `12` also available.

Is there any reason not to pick `jdk` `12` for **tag** **latest** ?

Regards,

**Comment by wimdeblauwe** [comment]
EA = Early Access

**Comment by waghanza** [comment]
And what about 9, 10 and 11 ?

**Comment by carlossg** [comment]
pointing latest to jdk 11
