### ISSUE TITLE
Update OpenJDK 8

### ISSUE THREAD

**Issue by bentatham** [carlossg/docker-maven#96]
Due to issues in openjdk 1.8.0_181 (specifically that affects [surefire](https://stackoverflow.com/questions/53010200/maven-surefire-could-not-find-forkedbooter-class/53096179)), it would be great to update the openjdk-8 images with the latest (1.8.0_191 or later).

**Comment by carlossg** [comment]
that comes from the openjdk docker image, see https://github.com/docker-library/openjdk/issues/247
